### ISSUE TITLE
Feature: Postgres Connection Pooling Control

### ISSUE THREAD

**Issue by dylanrhysscott** [hashicorp/boundary#1001]
**Is your feature request related to a problem? Please describe.**

I'm using a managed postgres database on Digitalocean which has pro rata connection limits via connection pooling - When running Boundary I don't see an option for controlling the number of connections made. A Boundary replica sometimes fails to start due to connection pool exhaustion. There are 3 controllers running each appearing to make 3 connections taking 9 connections total

**Describe the solution you'd like**

It would be really good to be able to specify the number of max connections a given controller can make to Postgres so I can control my usage and prevent Boundary from exhausting available connections. This could be added to Postgres configuration like below or via an env var:

```
controller {
...
  database {
    url = "postgresql://<username>:<password>@10.0.0.1:5432/<database_name>"
    max_connections = 1
  }
}

```

**Describe alternatives you've considered**

* I have considered scaling up my DO postgres database to increase possible connections which has a cost implication (This is only a pet project) 
* Scaling down my replicas
* Running a single controller pod and multiple workers

**Explain any additional use-cases**

I'm currently running Boundary on Kubernetes deployment with 3 replicas. Each replica runs as a controller and worker

**Additional context**
* My connection pool is a session pool - I had issues with transactional pools
* I am running a $15 DO Postgres instance
* Link to DO Postgres docs [https://www.digitalocean.com/docs/databases/postgresql/how-to/manage-connection-pools/](https://www.digitalocean.com/docs/databases/postgresql/how-to/manage-connection-pools/)

**Comment by dylanrhysscott** [comment]
Just to add more info:

Looking here I see Boundary uses Gorm  https://github.com/hashicorp/boundary/blob/main/internal/db/db.go#L31 - I think I'm running into issues with hitting the MaxIdleConnections. If the DB object returned on open follows the generic interface it should be possible to set some additional options around numbers of connections. [https://gorm.io/docs/generic_interface.html#Connection-Pool](https://gorm.io/docs/generic_interface.html#Connection-Pool)

**Comment by malnick** [comment]
Thanks for posting @dylanrhysscott - I'm going to escalate this to @jimlambrt.

**Comment by jimlambrt** [comment]
Ty for the suggestion and we can definitely add a configuration setting to override the max idle connections.  It's in our backlog now and we'll work on prioritizing it.

**Comment by dylanrhysscott** [comment]
Thanks @jimlambrt  @malnick Looking at the change I would be happy to have a go at this?

**Comment by dylanrhysscott** [comment]
@jimlambrt @malnick  I have a working implementation of this - Will open a PR shortly once I've tested
