### ISSUE TITLE
Boundary Desktop App reporting 403

### ISSUE THREAD

**Issue by hutger** [hashicorp/boundary#1002]
I have a set of users who **can list and connect** to Targets, Hosts and other resources using Boundary CLI, but using Boundary Desktop, they keep getting 403 error.

Role granted to the users: `id=*;type=*;actions=read,list,authorize-session`

**For 'admin' user everything works fine, the problem is with general users.** 

**Describe the bug**
I have a set of users who **can list and connect** to Targets, Hosts and other resources using Boundary CLI, but using Boundary Desktop, they keep getting 403 error.

**To Reproduce**

Using CLI the connection works fine:

```
$ export BOUNDARY_ADDR=http://boundary_host:9200

$ boundary authenticate password -auth-method-id=ampw_3uafhi6455 -login-name=lilian -password=password -format=json | jq -r ".token"
<TOKEN>

$ export BOUNDARY_TOKEN="<TOKEN>"                                                                                                                                        

$ boundary scopes list

Scope information:
  ID:                    o_1234567890
    Version:             1
    Name:                Generated org scope
    Description:         Provides an initial org scope in Boundary
    Authorized Actions:
      read

  ID:                    o_twK3uOKXeS
    Version:             1
    Name:                MyCorp
    Description:         My first scope!
    Authorized Actions:
      read

$ boundary scopes list -scope-id o_twK3uOKXeS
Scope information:
  ID:                    p_cskacqHkVR
    Version:             1
    Name:                Core infrastrcture
    Description:         My first project!
    Authorized Actions:
      read

$ boundary targets list -scope-id p_cskacqHkVR

Target information:
  ID:                    ttcp_W8wZn4kiqQ
    Version:             2
    Type:                tcp
    Name:                Backend SSH
    Description:         Backend SSH target
    Authorized Actions:
      read
      update
      delete
      add-host-sets
      set-host-sets
      remove-host-sets
      authorize-session

  ID:                    ttcp_XtwVzQawVk
    Version:             2
    Type:                tcp
    Name:                Backend RDP
    Description:         Backend RDP target
    Authorized Actions:
      read
      update
      delete
      add-host-sets
      set-host-sets
      remove-host-sets
      authorize-session
 
 
 $ boundary host-catalogs list -scope-id=p_cskacqHkVR

Host Catalog information:
  ID:                    hcst_WSy3itKkJV
    Version:             1
    Type:                static
    Name:                backend_servers
    Description:         Backend servers host catalog
    Authorized Actions:
      read
      update
      delete

$ boundary hosts list -host-catalog-id=hcst_WSy3itKkJV 

Host information:
  ID:                    hst_EFovASRCf4
    Version:             1
    Type:                static
    Name:                backend_server_service_10.0.1.30
    Description:         Backend server host
    Authorized Actions:
      read
      update
      delete

  ID:                    hst_ZkzWrtINzY
    Version:             1
    Type:                static
    Name:                backend_server_service_10.0.1.10
    Description:         Backend server host
    Authorized Actions:
      read
      update
      delete

  ID:                    hst_XQU3OeNlYB
    Version:             1
    Type:                static
    Name:                backend_server_service_10.0.1.20
    Description:         Backend server host
    Authorized Actions:
      read
      update
      delete

  ID:                    hst_VMgw3iwSsG
    Version:             1
    Type:                static
    Name:                backend_server_service_10.0.1.40
    Description:         Backend server host
    Authorized Actions:
      read
      update
      delete

$ boundary connect ssh -target-id ttcp_W8wZn4kiqQ -host-id hst_ZkzWrtINzY -username azureuser
The authenticity of host 'hst_zkzwrtinzy ([127.0.0.1]:51278)' can't be established.
ECDSA key fingerprint is SHA256:gOi0zuEOnDYNb1cAdRBoKG0lYTIQ5Wlaiy2vTjrBFV0.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'hst_zkzwrtinzy' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1040-azure x86_64)
```

The same user logged via WebUI:
![image](https://user-images.githubusercontent.com/19155362/111313112-3ccd4500-8660-11eb-8e4f-bf87af3c06eb.png)

But using the Desktop app, the same user gets 403:

![image](https://user-images.githubusercontent.com/19155362/111315147-61c2b780-8662-11eb-8068-d57678e1851b.png)

**Expected behavior**
User being able to list targets and open sessions the same way it does via CLI.

**Comment by malnick** [comment]
Thank you for posting this! We're taking a look this morning and will get back to you soon. As a note, I edited your post to remove `gents` because it does not reflect the makeup of our team.

**Comment by gsusmi** [comment]
Thanks for raising this @hutger.

The Boundary Desktop client is attempting to recursively load all targets/session within an org scope. From what I can tell, it looks like your user has listing capabilities set on the project scope, which works on Admin client as it's loading resources at project scope when you navigate to view targets/sessions within a project. In order for the Boundary Desktop client to list available targets/sessions from an org scope, you can assign your current `id=*;type=*;actions=read,list,authorize-session` permissions to an org scope or create listing capability on the org scope. If you choose to update scope for your current permissions, you can update this in Admin client by editing 'Settings > Grant Scope' in your role.

**Comment by hutger** [comment]
Hi @gsusmi , thanks for your quick reaction. I'm gonna give it a try and get back to you soon.

**Comment by gsusmi** [comment]
To clarify, the suggested approach is a workaround while we work on enhancements to refine recursive listing permissions to not need this bypass for Boundary Desktop.

In order to avoid providing read and list capabilities on all resources at org level, you should also specify them on just targets and sessions using `id=*;type=target;actions=read,list,authorize-session` and `id=*;type=session;actions=read,list`. Do note that this applies for all targets and sessions in your specified scope.

**Comment by hutger** [comment]
@gsusmi , it works now! 

I've added to my TF definitions a new role at the Org level with the suggested grants together with the desired principals. 

![image](https://user-images.githubusercontent.com/19155362/111515113-b6456000-8752-11eb-941a-5a035af78da2.png)

Just another remark (maybe this will require a new issue)... when a new role is added linked to a project scope, it is not listed on WebUI, although visible through CLI. It's pretty much an interface matter, but doesn't seem to affect the service.

``` 
...
resource "boundary_role" "linux_role" {
  name        = "linux_role"
  description = "linux role"
  principal_ids = [boundary_group.linux_group.id]
  grant_strings = ["id=*;type=*;actions=read,list,authorize-session"]
  scope_id    = boundary_scope.core_infra.id
...
}
```

**Comment by gsusmi** [comment]
Thank you for trying out the workaround!

Regarding role visibility in projects via the admin UI, we'll track the potential feature modification in our backlog. As a workaround, either configure project-specific roles via the CLI, OR if you'd like to use the Admin client, you can configure a role at the org level with project grant scope.

Attached screenshot displays 'Grant Scope' selection within a role at in org navigation in Admin. It can be used to re-assign to a project scope.
<img width="313" alt="grant-scope" src="https://user-images.githubusercontent.com/111036/111538424-0ae0df00-8743-11eb-86f4-78e923abe921.png">


Thanks again for trying out Boundary!

**Comment by akhila98** [comment]
Hello @gsusmi @malnick ,Actually when I am trying to connect a target using boundary desktop, my boundary cli is not starting, is there any permission/role to be assigned in order to start the cli. and also is there any other shell we can use instead of cli ,so that we can copy the address and then connect.
