### ISSUE TITLE
Manage Targets Common Workflows Tutorial typo

### ISSUE THREAD

**Issue by kphunter** [hashicorp/boundary#1013]
**Describe the bug**
Typo in Manage Targets tutorial for creating [Host Catalog via Terraform](https://learn.hashicorp.com/tutorials/boundary/manage-targets?in=boundary/common-workflows#add-hosts-to-project)

**To Reproduce**
1. Complete [Manage Scopes](https://learn.hashicorp.com/tutorials/boundary/manage-scopes) tutorial
2. Under "Add hosts to project", click "Terraform" tab
3. After running `terraform apply`, and `yes`, the following is generated:
```
boundary_host_catalog.devops: Creating...

Error: invalid type provided
```

**Expected behavior**
Host catalog resources is created successfully

**Additional context**
In the `boundary_host_catalog` resource, type should be `static`, not `Static`

**Comment by stellarsquall** [comment]
Fixed in [PR 3141](https://github.com/hashicorp/learn/pull/3141)

Thanks for reporting this, and suggesting the fix.
