### ISSUE TITLE
Attempting to delete a stale active session throws a duplicate key violation

### ISSUE THREAD

**Issue by dylanrhysscott** [hashicorp/boundary#1055]
**Describe the bug**

When deleting old stale but still active sessions Boundary reports the following error from the controller

```
2021-03-31T22:21:52.261Z [ERROR] controller: error performing termination of completed sessions: error="session.(Repository).TerminateCompletedSessions: db.DoTx: session.(Repository).TerminateCompletedSessions: db.Exec: duplicate key value violates unique constraint "session_state_session_id_end_time_key": unique constraint violation: 
```

**To Reproduce**

1. Open several sessions to the same target 
2. I think let the session timeout due to OS sleep or similar - I left a session or two open and my Mac went to sleep
3. Session apparently remains active even though the terminal process is no long running but unable to be deleted from 

**Expected behavior**

Sessions should be cancellable without a dependency violation

**Additional context**

I attempt to remove the session via the Boundary desktop application and CLI with same result

<img width="1298" alt="Screenshot 2021-03-31 at 23 33 56" src="https://user-images.githubusercontent.com/4922401/113219650-b167cc80-9279-11eb-9715-bc64f7c62c06.png">

The session I tried to cancel has long since been closed from the client but has remained stuck here

From the CLI same error is presented

```
➜  ~ boundary sessions cancel -id s_tURbHPlAvP
Error from controller when performing cancel on session:
Error information:
  Kind:                InvalidArgument
  Message:             Invalid request.  Request attempted to make second resource with the same field value that must be unique.
  Status:              400
➜  ~
```

Boundary CLI version

```
Version information:
  Git Revision:        bc565922fbd3a18c9f6a22cd2e80a93df0d7cd45
  Version Number:      0.1.7
```

Boundary Server Version

```
/ $ boundary version

Version information:
  Git Revision:        c0f33f982c87c0eb4127cb16cf06b03a37b91dbd
  Version Number:      0.1.8

/ $
```

I am running Boundary server in Docker on Kubernetes backed by Postgres

**Comment by rodrigocastrillon** [comment]
Hello. 

Same happens to me when I try to use a browser to connect to a target host. I also noticed that Firefox is not able to connect to the mapped port (connection timeout), while Chrome and Edge can (I see packets with tcpdump from worker to destination host), but connection is reset at some point. I am trying to connect to a Solar Winds https URL behind the worker.

After some testing I have several stale sessions that I am not able to cancel:
```
boundary sessions cancel -id=s_b3GKUGn7DG
Error from controller when performing cancel on session

Error information:
  Kind:                InvalidArgument
  Message:             Invalid request.  Request attempted to make second
  resource with the same field value that must be unique.
  Status:              400
  context:             Error from controller when performing cancel on session
```

Boundary CLI version
```
C:\> boundary version

Version information:
  Git Revision:        7bf6fad7e235ff9ba8fa904904afd1b6deb40082
  Version Number:      0.2.0
```

Boundary Server Version
```
# boundary version

Version information:
  Git Revision:        7bf6fad7e235ff9ba8fa904904afd1b6deb40082
  Version Number:      0.2.0
```

**Comment by Theragus** [comment]
Hi,
same problem here.
Quite confusing because this can happen at any time and stale sessions just keep stacking up.

<img width="1390" alt="Bildschirmfoto 2021-05-08 um 13 23 11" src="https://user-images.githubusercontent.com/38653346/117537404-eac1f380-b000-11eb-8672-229c66aaa2b8.png">

Boundary server version:

```
boundary -version

Version information:
Git Revision:        7bf6fad7e235ff9ba8fa904904afd1b6deb40082
Version Number:      0.2.0
```

**Comment by Theragus** [comment]
Another problem that I also noticed is that the Host, that the Session is associated with, can also not be deleted from the Boundary Hosts. 

It throws the same error message when there is a stale session still open.

**Comment by malnick** [comment]
Thank you for submitting this, we'll be looking into this issue soon!

**Comment by jefferai** [comment]
If there is interest in trying out a build that we think should significantly improve this issue, please let me know. It'd require database migrations so it's a one-way upgrade (other than restoring the DB from a snapshot) and it would be nearly identical to the upcoming 0.2.2 release (at least, as currently planned). If so, let me know which platforms you need builds for.

**Comment by jefferai** [comment]
I put some binaries in #894

**Comment by the-maldridge** [comment]
Any suggestions for a workaround until this gets a permanent fix?

**Comment by jefferai** [comment]
@the-maldridge as you're not the OP it'd be helpful to get some exact error cases/messages (especially from the CLI).

Also, from any of you, it would be great if you're able to give us dumps of your database (we can give you a private place to put it). We wouldn't need the KMS keys -- we don't need to decrypt anything, this would just help us understand the state things are in within the data model, which makes it far easier to understand how they can get there. Totally understand if you don't feel comfortable, but if you do it would help.

**Comment by the-maldridge** [comment]
@jefferai sure, my error messages are as shown above, but for completeness here's an error I just pulled trying to cancel a long defunct session from last week on the CLI.

```
$ boundary sessions cancel -id s_ZbBlOXlJIU
Error from controller when performing cancel on session

Error information:
  Kind:                InvalidArgument
  Message:             Invalid request.  Request attempted to make second resource with the same field value that
  must be unique.
  Status:              400
  context:             Error from controller when performing cancel on session
```

I'm still relatively early on in my setup and can easily provide you a complete pg_dump somewhere that isn't a globally visible github issue ticket.

**Comment by the-maldridge** [comment]
I should add that I can cancel some kinds of sessions, but they sit forever in `cancelling`.  I'm not yet sure what makes these sessions different.

**Comment by jefferai** [comment]
@the-maldridge can you send me an email at jeff at the-company-i-work-for dot com? I'll send you a link to a google drive folder where you can upload a pg_dump. Thanks so much!

**Comment by the-maldridge** [comment]
I love the anti-spam technique.  Email sent.

**Comment by the-maldridge** [comment]
@jefferai following up on this and double checking that my email made it to you.

**Comment by jefferai** [comment]
Yep -- sorry, I was OOO much of yesterday. Replied to your email!

**Comment by the-maldridge** [comment]
No worries, I completely understand.  I've sent the archive via email, please let me know if there's any other information I can pull to assist in debugging this issue.  Databases are far from my specialty, but I'm happy to try things here as understanding of this bug develops.

**Comment by MikaDiablo** [comment]
Do we have any update on this issue ? because i have the same bug and i am using 0.6.2 version of boundary server and 1.3 for the UI

**Comment by jimlambrt** [comment]
we are working on a fix for this.  I believe, this issue and https://github.com/hashicorp/boundary/issues/1724 are related.

**Comment by the-maldridge** [comment]
Interesting.  I don't know if it is useful to know or not, but I think that I started seeing issues just after 2 weeks of having the controllers up and running.  I deployed in a very piece wise way while I got stuff up and running.

**Comment by swapnil-raj** [comment]
Hello. I am using 0.7.1 version of boundary and i also see the same error message in the controller logs. I have deployed both controller and worker on k8s. Any session which i cancel doesn't gets terminated, Instead they are on "cancelling" state.

**Comment by the-maldridge** [comment]
Happy New Year!  Any update on this issue or potential workaround?  I looked through the 0.7 changelog and didn't see anything that looked relevant here.  I'm hesitant to upgrade with the database in an inconsistent state, and I really would like to evaluate the automatic host groups which are only in the latest version.

**Comment by jefferai** [comment]
👋 See #1793 where work is going on to address this. I will let @irenarindos comment on any specifics and whether there will be future follow-on work needed.

**Comment by the-maldridge** [comment]
Thanks for the pointer.  I'll subscribe to updates on that ticket.

**Comment by irenarindos** [comment]
Changes in #1793 will prevent sessions from transitioning between invalid states (ex: from canceling to active) and will also prevent duplicate session states (ex: a session_id has two rows with state active). This bug fix should resolve the issues reported on this ticket, but if it does not, please reach out to us with feedback.

**Comment by the-maldridge** [comment]
Fantastic.   I'll keep an eye out for the next release that includes that fix.  Is there additional work that's expected to be required to clean up already invalid database state?
