### ISSUE TITLE
Boundary Desktop can not connect to boundary with cors origin

### ISSUE THREAD

**Issue by maksim-paskal** [hashicorp/boundary#1093]
Boundary Desktop can not connect to boundary with cors origin

**To Reproduce**
1. enable `cors_allowed_origins` in boundary config
```
listener "tcp" {
  address = "0.0.0.0:9200"
  purpose = "api"

  tls_disable = false
  tls_cert_file = "/certs/server.crt"
  tls_key_file  = "/certs/server.key"
  tls_min_version = "tls13"

  cors_enabled = true
  cors_allowed_origins = ["https://example.com"]
}
```
2. open Boundary Desktop and try to login

**Additional context**
If enable electon-debug in source code of Boundary Desktop
```
const debug = require('electron-debug'); debug();
```
there is a problem in console
```
Access to XMLHttpRequest at 'https://example.com/v1/scopes' from origin 'serve://boundary' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by jefferai** [comment]
See https://www.boundaryproject.io/docs/configuration/listener/tcp#cors_allowed_origins -- I think the issue is that when you set a custom `cors_allowed_origins` you removed `serve://boundary` which is the origin used by the desktop client.

**Comment by jefferai** [comment]
For 0.2.1 we'll default to adding `serve://boundary` in all cases, and add a flag that lets you disable this. So even if you define custom CORS, by default, the desktop client will still work.
