### ISSUE TITLE
[Question] Where is Documentation Code? :/

### ISSUE THREAD

**Issue by mukeshkmr776** [hashicorp/boundary#1142]
Unable to find Documenation Code in this repository. Please help me find it. 

Looking for code for documenation which is hosted on below URL:
https://learn.hashicorp.com/tutorials/boundary/getting-started-intro?in=boundary/getting-started

**Comment by mukeshkmr776** [comment]
@jefferai @mgaffney

**Comment by mgaffney** [comment]
Hi @mukeshkmr776, thanks for the question. Currently, the learn code/content is not open source but you can open issues here for any problems you find or suggestions you might have.

**Comment by jefferai** [comment]
Hi @mukeshkmr776 ,

The issue tracker is reserved for bugs and feature requests. Please use [our forums](https://discuss.hashicorp.com/t/where-is-documentstion-code-in-github-repository-for-boundaryproject/23288) for general questions. Thanks!
