### ISSUE TITLE
Authenticate with openid connect formatted as json returns disturbing text

### ISSUE THREAD

**Issue by denniskniep** [hashicorp/boundary#1193]
**Describe the bug**

Authenticate with openid connect authentication method. And return response as json.
It will return following text, before json response:
```
Opening returned authentication URL in your browser...
```

That is a problem if you will further process the json response i.e. with `jq`

**To Reproduce**
1. `boundary authenticate oidc -auth-method-id amoidc_123456 -format=json | jq -r '.item.token'`

**Comment by malnick** [comment]
Thank you for submitting this and the associated PR!
