### ISSUE TITLE
Feat: Add OIDC claim-to-role mapping

### ISSUE THREAD

**Issue by MChorfa** [hashicorp/boundary#1202]
It would be nice if the authenticated user have a certain role, get auto mapped to the target role within Boundary

**Comment by adubkov** [comment]
It would be better if user's OIDC group would auto mapped to Boundary group.

**Comment by adubkov** [comment]
We are using okta group to boundary group mapping, then boundary group set as principal for specific role.
Here is a commit that works for us https://github.com/adubkov/boundary/commit/82066218cb8a9db991be812c163cc1ed7ed97a11 just for anyone who need it until boundary team will implement.

**Comment by PPacent** [comment]
Hi @MChorfa and @adubkov this functionality is now available with Boundary's Managed Groups feature, which allows you to define sync Boundary IAM permissions with those of an external identity provider by mapping identity provider claims to group memberships in Boundary. You can read more about this feature here: https://www.boundaryproject.io/docs/concepts/domain-model/managed-groups

I will close out this thread as the feature is now available, but let us know if you have any questions!

**Comment by MChorfa** [comment]
Thank you for making this happen 🎉
