### ISSUE TITLE
Groups membership cli help is not accurate

### ISSUE THREAD

**Issue by adubkov** [hashicorp/boundary#1208]
The help shows an example
```bash
$ boundary groups add-members -id g_1234567890 -user u_1234567890
```

Bun when I run it returns: `flag provided but not defined: -user`

The right flag name is `member`:

```bash
$ boundary groups add-members -id g_1234567890 -member u_1234567890`
```

This is simple fix just need to decide is it actually user or member - I like `user` more but `member` is better align with other code.

**Comment by malnick** [comment]
Thank you for the PR!
