### ISSUE TITLE
Public IP addresses being used despite Workers and Controllers are in the same subnet when public IP is set in the controller config

### ISSUE THREAD

**Issue by Theragus** [hashicorp/boundary#1219]
**Describe the bug**
We have deployed 3 Controllers and 3 Workers in a subnet in Azure.
The 3 Controllers are sitting behind a Layer 7 Load Balancer which forwards 9200 to the controllers. Port 9201 is not forwarded because the Workers and Controllers seem to be using their own flavour of TLS and are unable to speak over the L7 Load Balancer.
Workers are deployed in the same subnet as the controllers and have public IPs but no Load Balancer in front of them. The public IP of the worker is set in the config of each worker.

When setting the public IP address in the Controllers Config, the Workers try to connect to the public IP set in the Controllers config. From the docs over at https://www.boundaryproject.io/docs/installing/high-availability I would assume that the connection to the Controllers from the Workers is remaining in the private subnet, but setting the public IP on the Controllers forces the Workers to go over the public IP. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a controller with public IP and set the public IP in the controller config
2. Set up a worker and establish a connection with the controller in the same subnet
3. The worker will force its connection to the controller over the public IP instead of over the private connection in the subnet.

**Expected behaviour**
Workers reach the controllers on port 9002 inside the private subnet.

**Additional context**
The background for setting the Public IP in the Controller config is that we have Workers deployed in other clouds and locations. Therefore we need to set the public IP in the controller config for other Workers not in the Azure Subnet to reach the controller.

**Comment by jefferai** [comment]
> The public IP of the worker is set in the config of each worker.......The background for setting the Public IP in the Controller config is that we have Workers deployed in other clouds and locations. Therefore we need to set the public IP in the controller config for other Workers not in the Azure Subnet to reach the controller.

This is the root of your issue -- we use the address we're given, and since the address you're giving is the public IP, that's going to be used by all workers. 

For more information about TLS between workers and controllers, see https://www.boundaryproject.io/docs/concepts/security/connections-tls#worker-to-controller-tls
