### ISSUE TITLE
duplicate key value violates unique constraint errors

### ISSUE THREAD

**Issue by xaevman** [hashicorp/boundary#1303]
**Describe the bug**

When trying to delete host sets, hosts, and targets that are no longer in use via the Boundary Terraform provider I often receive error messages stating "Invalid request. Request attempted to make second resource with the same field value that must be unique", and the operation fails. This error message is also present if I try to manually delete the items via the Boundary web interface.

![image](https://user-images.githubusercontent.com/3894743/121423852-8eb2fd80-c925-11eb-8bc9-bc96a6a0b9cc.png)

Additionally, the Boundary process seems to be producing these logs constantly...

`Jun 09 20:18:41 ip-10-24-80-235 boundary[1342]: 2021-06-09T20:18:41.193Z [ERROR] controller: error performing termination of completed sessions: error="session.(Repository).TerminateCompletedSessions: db.DoTx: session.(Repository).TerminateCompletedSessions: db.Exec: duplicate key value violates unique constraint "session_state_session_id_end_time_key": unique constraint violation: integrity violation: error #1002"`

**To Reproduce**
It does not always happen, but the sequence in which it often happens goes like this
1. Populate Hosts, Host Set, Target, and Target -> Host Set links via Boundary Terraform config
2. At some future point in time, scale down the infrastructure (remove hosts, or even entire sets)
3. Re-run terraform with updated configuration to remove outdated Host Set and Host entries

**Expected behavior**
Boundary references to assets that no longer exist are removed appropriately.

**Additional Context**
After seeing https://github.com/hashicorp/boundary/issues/1055 and https://github.com/hashicorp/boundary/issues/894 I upgraded to Boundary server 0.2.3 and ran the database migrations successfully but the error persists.

**Comment by jefferai** [comment]
Tagging @jimlambrt -- we think that this is distinct from #894.

**Comment by jefferai** [comment]
Would you be able to capture the error you get when deleting when using the CLI? The UI and TF might be hiding some useful information. It would also be good to know if you see logs related to the deletion operation distinct from the session issue you're seeing above.

**Comment by monty16597** [comment]
Hello @jimlambrt , any update on this issue ?

**Comment by rjshrjndrn** [comment]
yup.. Now all the connections are closing immediately after being created. For example, if I create an ssh connection, and use the port to ssh, I'll successfully login, but the connection will get terminated, and I have to start the entire process once again.

**Comment by jefferai** [comment]
@rjshrjndrn Can I ask you to open a new ticket for that? Just to keep this ticket specifically around duplicate key issues. Thanks!

**Comment by rjshrjndrn** [comment]
@jefferai thanks for the pointer.  I've created another ticket https://github.com/hashicorp/boundary/issues/1724
Please lemme know, if you need any other info.
