### ISSUE TITLE
RunJobs check contstraint failed

### ISSUE THREAD

**Issue by umglurf** [hashicorp/boundary#1309]
**Describe the bug**

Since boundary 0.2.3 I've started getting these errors in the controller logs:
```
[ERROR] controller: error getting jobs to run from repo: error="job.(Repository).RunJobs: db.DoTx: job.(Repository).RunJobs: wt_private_id_check constraint failed: check constraint violated: integrity violation: error #1000"
```
I upgraded to 0.3.0 hoping the issue was solved, but still the same. I then deleted the database and recreated it, but still the error occurs.

**To Reproduce**
1. Start boundary-controller
2. See error

**Expected behavior**

**Additional context**
Running with 3 boundary controllers and 4 workers. 3 workers on the same servers as the controllers, and one worker on another server.

**Comment by louisruch** [comment]
Hi @umglurf 
Thank you for trying Boundary!  I noticed this issue when running `boundary dev` and discovered it was a race between the server upsert and the new job scheduler requesting work.  I resolved this in a wip branch with other work, but I forgot to merge this fix into main - sorry about that.  However, since you are not running Boundary in dev mode it might not be the same race I found, do you see this error consistently or only once when starting the server?

**Comment by umglurf** [comment]
Hi

I see it consistently, not only when starting the server. It's been logged about 50 times per server since the last restart one hour ago.

**Comment by louisruch** [comment]
@umglurf 50 times in an hour is about what I would expect from this, you mentioned that you have 3 controllers are you providing the name in the [controller stanza](https://www.boundaryproject.io/docs/configuration/controller#controller-stanza).  If so can you please confirm what the three names are?

**Comment by umglurf** [comment]
controller 1:
```
name = "kara"
```
controller 2:
```
name = "sharon"
```
controller 3:
```
name = "laura"
````

**Comment by louisruch** [comment]
Thank you!

There is a bug in the Postgres job_run table where we are incorrectly enforcing a check constraint on the length on the controller name to be greater than 10.  I have a [PR](https://github.com/hashicorp/boundary/pull/1310) that should resolve this issue.

**Comment by umglurf** [comment]
Great, hoping this will make it into 0.3.1
