### ISSUE TITLE
Feature: Bondary Desktop for Linux

### ISSUE THREAD

**Issue by maksim-paskal** [hashicorp/boundary#1381]
Our users use Linux (Ubuntu) - and Bondary Desktop that run on Linux will helps to migrate that users from SSH tunels (that mostly used in MySQL Workbench) to Boundary

**Comment by PPacent** [comment]
Thanks for the suggestion @maksim-paskal. While Boundary Desktop currently supports MacOS and Windows, we are investigating adding support for Linux distributions for a future update. We will keep this request open so that the community can upvote and show their support!

**Comment by gedw99** [comment]
Is the desktop code open ?

mid it electron based ?

**Comment by derrickmehaffy** [comment]
> Is the desktop code open ?
> 
> mid it electron based ?

Yes the boundary-UI is here: https://github.com/hashicorp/boundary-ui



> Thanks for the suggestion @maksim-paskal. While Boundary Desktop currently supports MacOS and Windows, we are investigating adding support for Linux distributions for a future update. We will keep this request open so that the community can upvote and show their support!

@PPacent is there a timeline for this? Any key challenges your team has identified or any information you can provide if someone wanted to contribute?

**Comment by PPacent** [comment]
Closing this item out as Boundary Desktop supports debian-based linux distributions as of [Boundary 0.6](https://www.hashicorp.com/blog/announcing-hashicorp-boundary-0-6 ) and Boundary Desktop 1.3. You can download the latest Boundary Desktop distributions [here](https://www.boundaryproject.io/downloads).

For any additional linux distributions please feel free to create a [new feature request](https://github.com/hashicorp/boundary-ui/issues/new?assignees=&labels=&template=feature_request.md&title=) so the Boundary team can gauge interest.

**Comment by derrickmehaffy** [comment]
> Closing this item out as Boundary Desktop supports debian-based linux distributions as of [Boundary 0.6](https://www.hashicorp.com/blog/announcing-hashicorp-boundary-0-6) and Boundary Desktop 1.3. You can download the latest Boundary Desktop distributions [here](https://www.boundaryproject.io/downloads).
> 
> For any additional linux distributions please feel free to create a [new feature request](https://github.com/hashicorp/boundary-ui/issues/new?assignees=&labels=&template=feature_request.md&title=) so the Boundary team can gauge interest.

Awesome, Thank you @PPacent and the Hashicorp team!
