### ISSUE TITLE
Boundary Desktop - black window, no interface

### ISSUE THREAD

**Issue by magzim21** [hashicorp/boundary#1388]
**Describe the bug**
Boundary's Desktop app is just black after opening. No interface.
It was ok right after installation, but after 1 day of usage I have this issue.

**To Reproduce**
I am not sure how to reproduce, but it happened after I had changed dev version of Boundary to prod version on a remote host (boundary was connected there).

Whatever I try does not fix it. I tried:
- `boundary logout`  shell command
- restart my computer
- cleanMyMac app
- reinstalling Desktop app

**Expected behavior**
Just opens interface, not black window

**Additional context**
MacOs 11.2.1
Boundary 0.4

<img width="1680" alt="Screenshot 2021-07-08 at 23 22 01" src="https://user-images.githubusercontent.com/46382297/124997868-4f222300-e043-11eb-9f4b-a1f947eaa09d.png">

**Comment by malnick** [comment]
Sorry to hear you're having trouble with our desktop client. 

> changed dev version of Boundary to prod version on a remote host

Am I reading this correctly in that you pointed the DT client to another instance of Boundary? If so, can you verify if the version changed between the two instances?

Also, can you grab the version of the DT client in the `About` dropdown menu so we can verify what version you're on there? 

Thanks!

**Comment by magzim21** [comment]
I did very many actions because I was having difficulties with non-dev installation, one of actions was switching between versions (downgraded controller to 0.3).

DT client version is :
Version:  1.2.0
Commit: 7413afb11df9536af169507197c4eb1bf1e5e9e6

**Comment by gsusmi** [comment]
Ty for the client info! Seeing as the desktop client is not able to connect to a non-dev instance, I'm wondering if the non-dev instance CORS config allows for desktop client access. By default, desktop's origin is appended to CORS origins list on controller, unless `cors_disable_default_allowed_origin_values` is specified.

Ref: https://www.boundaryproject.io/docs/configuration/listener/tcp#cors_allowed_origins

**Comment by magzim21** [comment]
In my case all all CORS settings are default.
UPD: DT client started to work normally after I connected to the same server with cli oidc. Idk.

**Comment by gsusmi** [comment]
Ty for the update!

**Comment by gsusmi** [comment]
Closing this out for now. Ty
