### ISSUE TITLE
Running boundary dev on Windows 10 yields error message

### ISSUE THREAD

**Issue by pcgeek86** [hashicorp/boundary#1394]
**Describe the bug**

Running `boundary dev` on Windows 10 results in error message.

**To Reproduce**
1. `scoop install boundary`
1. Run `boundary dev`
1. See error

```
PS C:\> boundary dev
Error initializing listener of type tcp: listen tcp 127.0.0.1:9200: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

**Expected behavior**

According to the [tutorial](https://learn.hashicorp.com/tutorials/boundary/getting-started-dev?in=boundary/getting-started), a dev environment should be spun up.

**Additional context**

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.21387
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jefferai** [comment]
There are all sorts of reasons why this could occur so I don't have any particular way forward, but I will say that it is reminiscent of a problem I've seen a lot on Windows with Docker where Docker can choose ports for exposed ports on containers that conflict with reserved port ranges within Windows. See the discussion within https://github.com/docker/for-win/issues/3171#issuecomment-788808021 and in particular that comment for what works for me when I see a similar error with Docker, and in that issue you can see commands for displaying reserved port ranges.

**Comment by PPacent** [comment]
Closing this as there aren't additional responses or issues raised and @jefferai's guidance above likely provides a solution.
