### ISSUE TITLE
Location Header Rewriting for HTTP Targets

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/boundary#1461]
**Is your feature request related to a problem? Please describe.**
Yes.  If an application server sends a HTTP 301, 302, or 303 redirect, the ephemeral destination port used by the client is not included.  This causes the client browser to navigate to the wrong resource.  For example, imagine the following:
```
Client (TCP/54321) > Boundary Worker > ALB (80) > App Server > nginx (80)
```
The client navigates to `/` and the application sends a 302 redirect to `/login`.  From Nginx's perspective, the request port from the ALB is 80.  And the ALB passes header `X-Forwarded-Port` which is also 80.  So the header reads `Location: http://127.0.0.1/login`.  The location header needs to be modified to include the ephemeral port being used by the client.

I've looked through the docs, discussion forum, and GitHub issues but couldn't find any mention of this issue yet.  I also created a question on the discussion forum:  https://discuss.hashicorp.com/t/http-301-302-and-303-redirects-with-ephemeral-ports/28217

**Describe the solution you'd like**
Boundary workers should update the Location header in the response to ensure client browsers will navigate to the URI over the correct ephemeral port established by Boundary.  An alternative I suppose could be to send a `X-BOUNDARY-PORT` header, which nginx could use to do location header rewriting.

I'm also not sure how this could work with HTTPS.

**Comment by PPacent** [comment]
Closing this issue as there haven't been any other upvotes and @micchickenburger found a workaround.
