### ISSUE TITLE
Session stuck in stale status and can't cancel it.

### ISSUE THREAD

**Issue by Robin-Ding-Bose** [hashicorp/boundary#1472]
**Describe the bug**
I found some abnormal session status from client UI , cli and admin console.
From cli:
```
./boundary sessions read -id s_etqKSPU3Kr       
Session information:
  Auth Token ID:        at_h9fbmpLjTy
  Created Time:         Wed, 18 Aug 2021 16:02:48 CST
  Endpoint:
  tcp://database-2.chth3zso2ffq.rds.cn-northwest-1.amazonaws.com.cn:5432
  Expiration Time:      Thu, 19 Aug 2021 00:02:48 CST
  ID:                   s_etqKSPU3Kr
  Status:               canceling
  Termination Reason:   connection limit
  Type:                 unknown
  Updated Time:         Wed, 18 Aug 2021 16:05:05 CST
  User ID:              u_7Jjba4Dxms
  Version:              2

  Scope:
    ID:                 p_Ai4NzKYQDz
    Name:               core_infra
    Parent Scope ID:    o_pUME8fizyk
    Type:               project

  Authorized Actions:
    no-op
    read
    read:self
    cancel
    cancel:self

  States:
    Start Time:         Wed, 18 Aug 2021 16:04:57 CST
    Status:             canceling

    End Time:           Wed, 18 Aug 2021 16:04:57 CST
    Start Time:         Wed, 18 Aug 2021 16:03:20 CST
    Status:             terminated

    End Time:           Wed, 18 Aug 2021 16:03:20 CST
    Start Time:         Wed, 18 Aug 2021 16:03:19 CST
    Status:             active

    End Time:           Wed, 18 Aug 2021 16:03:19 CST
    Start Time:         Wed, 18 Aug 2021 16:02:48 CST
    Status:             pending
```
The status stuck in 'canceling'.

For UI
![image](https://user-images.githubusercontent.com/76583568/130001453-c2847c67-5353-4eb7-a34f-a75fd40e9353.png)
Even no any other session listed.

For Admin Console
![image](https://user-images.githubusercontent.com/76583568/130001970-5dc9e755-96bc-4718-a614-76bf59004401.png)
If I click the "Cancel", the console would show the hint "Success Canceled successfully." and the status become "canceling".  But several seconds later, the status become "active" again.

**To Reproduce**
I am sorry I don't know how to reproduce the issue.

**Expected behavior**
The session list should show the correct session status.

**Additional context**
I deploy the boundary docker image v0.5.0 in AWS ECS Fargate.
For ECS Fargate doesn't support IPC_LOCK, I set the $SKIP_SETCAP environment in docker-entrypoint.sh
I use AWS RDS Postgres as the database.
I use AWS ALB to forward access to the admin console endpoint.
I use AWS NLB to forward access to the worker endpoint.

May I just delete all records in some table to clear all sessions info to fix this issue?
Thanks.

**Comment by vancluever** [comment]
@Robin-Ding-Bose thanks for the report. We've seen a few of these reports now but have haven't been able to reproduce it.

A few things:

* Can you tell me about the target setup?
* Have you been able to reproduce this just using `boundary dev` and a local Docker desktop?

Thanks!

**Comment by Robin-Ding-Bose** [comment]
@vancluever 

I deploy the resources based on https://github.com/hashicorp/boundary-reference-architecture.
After all basic resources have been deployed, I create another RDS Postgres instance database-2 manually with proper security group.
Then I add the database-2 info into the terraform template of the above repo and create the target by template.

I haven't deployed the resources using boundary dev and a local Docker desktop yet.
I would try if I have time this week, but I am not sure if I can reproduce this issue.

**Comment by vancluever** [comment]
@Robin-Ding-Bose yeah if you can that'd be great, it would be great data for us. Thanks!

**Comment by Robin-Ding-Bose** [comment]
@vancluever 
I have deployed the boundary in dev mode on my laptop. 
Also create the target to my database in docker container.
But I can't reproduce the issue in dev mode.
