### ISSUE TITLE
Replace lib/pq by jackc/pgx

### ISSUE THREAD

**Issue by umglurf** [hashicorp/boundary#1481]
**Is your feature request related to a problem? Please describe.**

[lib/pq](https://github.com/lib/pq) is in maintenance mode and has been for a while. In the README they also recommend to change to [pgx](https://github.com/jackc/pgx). 

One of the features missing is [multi-host](https://paquier.xyz/postgresql-2/postgres-10-multi-host-connstr/) support, there is [a PR from 2018](https://github.com/lib/pq/pull/714) that has not been merged because there is no development resources. This makes it possible to simplify postgresql redundancy for many use cases. For instance [pg_auto_failover](https://github.com/citusdata/pg_auto_failover) depends on this and to some degree also [repmgr](https://repmgr.org).

**Describe the solution you'd like**

Boundary switches over to pgx or another maintained postgresql library which support what is now considered standard postgresql client features.

**Describe alternatives you've considered**

**Explain any additional use-cases**

**Additional context**

See also [same issue for terraform](https://github.com/hashicorp/terraform/issues/29284)

**Comment by jefferai** [comment]
Definitely something we're thinking about! I can't give a timeframe yet as we would need to do a bunch of due diligence and testing, but we're aware that we need to evaluate this. I'll keep this open to make sure we don't lose track.

**Comment by jimlambrt** [comment]
Addressed in the following PRs:
- https://github.com/hashicorp/boundary/pull/1535
- https://github.com/hashicorp/boundary/pull/1528
