### ISSUE TITLE
Error with Gsuite OIDC

### ISSUE THREAD

**Issue by ichasco-heytrade** [hashicorp/boundary#1662]
Hi! I have configured the OIDC login with Gsuite and my user can authenticate, but I am not able to grant any permission to it.

terraform config:
```
resource "boundary_auth_method_oidc" "google" {
  name               = "Google"
  description        = "OIDC auth method for Google"
  scope_id           = boundary_scope.org.id
  issuer             = "https://accounts.google.com"
  client_id          = "XXXXXXXXXXXXXXXXXXXXXX"
  client_secret      = "XXXXXXXXXXXXXXXXXXXXXXx"
  signing_algorithms = ["RS256"]
  api_url_prefix     = "http://127.0.0.1:9200"
  state                = "active-public"
  is_primary_for_scope = true
  account_claim_maps = [
    "email=email",
    "name=name",
    "sub=sub"
  ]
  claims_scopes = [
    "email",
    "profile"
  ]
}

resource "boundary_managed_group" "org" {
  name           = "group_test"
  description    = "An example of an OIDC managed group"
  auth_method_id = boundary_auth_method_oidc.google.id
  filter         = "\"mail.com\" in \"/userinfo/email\""
}

resource "boundary_role" "admin" {
  name          = "List and Read"
  description   = "List and read role"
  principal_ids = [
    boundary_managed_group.org.id,
    boundary_group.devops.id
    ]
  grant_strings = ["id=*;type=*;actions=*"]
  scope_id      = boundary_scope.org.id
}
```
Output:
```
managed-group-id = "mgoidc_YXQZr0mUdg"
```

If I get the users in this group:
```
Managed Group information:
  Auth Method ID:      amoidc_szyHWH4uJo
  Created Time:        Wed, 03 Nov 2021 20:50:21 CET
  Description:         An example of an OIDC managed group
  ID:                  mgoidc_5uStcgrUc2
  Name:                group_test
  Type:                oidc
  Updated Time:        Wed, 03 Nov 2021 20:51:02 CET
  Version:             2

  Scope:
    ID:                o_kOIfn7NmeQ
    Name:              Org
    Parent Scope ID:   global
    Type:              org

  Authorized Actions:
    no-op
    read
    update
    delete

  Member IDs:
    acctoidc_uNOjG0WbZm

  Attributes:
    Filter:            "mail.com" in "/userinfo/email"

```

This is my user ID but when I log in in the desktop app I can't see any target.

And also, the `managed_group` are not shown in the web.

Thanks!

**Comment by grantorchard** [comment]
Thanks for logging this, I can reproduce your issue. To resolve this you should apply the role to the project scope id rather than the org scope id. 

```
resource "boundary_role" "project_admin"{
  name          = "List and Read"
  description   = "List and read role"
  principal_ids = [
    boundary_managed_group.org.id
    ]
  grant_strings = ["id=*;type=*;actions=*"]
  scope_id      = "o_kOIfn7NmeQ" # for example, create the role in the org, so it's managed here
  target_scope_id = "p_GV9rWIu4Xb" # apply it to the project scope
}
```

**Comment by ichasco-heytrade** [comment]
Hi @grantorchard,

What version of the provider are you using? in the last version of the provider `1.0.5` the schema `target_scope_id` doesn't exists. I have tried with `scope_id` adding the project ID and it worked. Thanks!

And If I want to grant access to all organization projects, Do I have to do it individually by project? Is not any other way?

Also I have another question. How Gsuite doesn't pass the groups in the JWT the only way is to use the API (like with vault). Is this in the roadmap?

For the moment if I want to grant permissions to OIDC users I have to do something like this (I don't know if it is any better solution)
```

resource "boundary_role" "admin" {
  name          = "List and Read"
  description   = "List and read role"
  principal_ids = [
    boundary_group.devops.id
    ]
  grant_strings = ["id=*;type=*;actions=*"]
  scope_id      = boundary_scope.project.id
}

resource "boundary_group" "devops" {
  name        = "devops"
  description = "My first group!"
  member_ids  = [
    "u_gaDsC5emvO" // my user
  ]
  scope_id    = boundary_scope.org.id
}
```

Thanks!

**Comment by grantorchard** [comment]
My apologies - the correct attribute is `grant_scope_id`. That will teach me to go from memory!

**Comment by ichasco-heytrade** [comment]
> My apologies - the correct attribute is `grant_scope_id`. That will teach me to go from memory!

Thanks @grantorchard, with this perfect. Is better to have the `scope_id` for the org and the `grant_scope_id` for the project, to can manage the role from the web? If you add in `scope_id` the project, you wouldn't manage it. Isn't it?

**Comment by grantorchard** [comment]
Yes, that's exactly the idea.

For granting access to all projects, [this resource table](https://www.boundaryproject.io/docs/concepts/security/permissions#resource-table) is a really good reference, though a little overwhelming at first.

You could probably do a little bit of Terraform loop magic to assign them like so:
```
resource "boundary_role" "this" {
  for_each = toset(local.project_ids)
  scope_id       = "your_org_id"
  grant_scope_id = each.value
  grant_strings = [
    id=<id>;type=scope;actions=*
]

  principal_ids = [
		boundary_managed_group.this.id
	]
	name = "scope_admin-${each.value}"
}
```

I

**Comment by ichasco-heytrade** [comment]
But in the `scope_id` if you add the org (only), at least it wouldn't work if you use OIDC. You have to add or only the project or the org and the project.

Sorry for the mess and thank you for the help :)
