### ISSUE TITLE
More helpful error messages desired on conflicting resources

### ISSUE THREAD

**Issue by peterlindsten** [hashicorp/boundary#1752]
Using Terraform to set up resources sometimes results in Terraform not saving state of a resource that was created, but failed to configure fully (Sending invalid IDs in `principal_ids` on `boundary_role` can cause this, among other things). Resulting in this error message upon a second `terraform apply`
```
boundary_role.cloudadmin: Creating...
╷
│ Error: error calling create role: {"kind":"InvalidArgument", "message":"Invalid request.  Request attempted to make second resource with the same field value that must be unique."}
│
│   with boundary_role.cloudadmin,
│   on main.tf line 96, in resource...
```

Then you have to import the previously created resource, to be able to apply changes to it - but the error message doesn't include the ID of the conflicting resource. In the Azure ARM provider of terraform, it gives you the ID (or part of) so you can import straight away, without checking somewhere else.

To me it looks like the JSON error is coming straight from Boundary, and could include the ID of the conflicting resource, thus making imports (or changes if you're at the CLI) much easier.

Alternatively for the specific Terraform case, the provider could be updated to understand that a resource is partially created (unsure if Terraform supports this? Also might be the wrong GitHub repo for such a change)

Importing resources into Terraform created elsewhere is also easier if this error reported ID, since you could make a `.tf` file with the same named resources, run `apply` import the conflicts, then apply again.

**Comment by louisruch** [comment]
@peterlindsten I have a PR open that resolves the specific issue around the Terraform state with regards to roles, I will add a couple more PRs during this week to update other resources with similar `SetX` paths, thank you for pointing this out to us!

With regards to more helpful error messages, we specifically do not include resource IDs as the resource in question might be out of your permission scope to see. We do however agree we can provide some more information than the current generic unique violation error you linked above.
