### ISSUE TITLE
Getting `remote error: tls: bad certificate` on one worker node after upgrading to 0.7.x

### ISSUE THREAD

**Issue by evanravenelle** [hashicorp/boundary#1814]
**Describe the bug**

Attempting to connect to a target using `boundary connect ssh` results in intermittent failures.  The failures occur when the controller routes the client to a specific worker node, which then fails when dialing the worker node.  The failures occur regardless of the specified scope and/or target.  Example output is below.

```
iac/dev » boundary connect ssh -target-scope-name testbuild1 -target-name test-node -- -l ubuntu
Error dialing the worker: failed to WebSocket dial: failed to send handshake request: Get "https://54.x.x.x:9202/v1/proxy": remote error: tls: bad certificate
kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 43971
error fetching connection to send session teardown request to worker: Error dialing the worker: failed to WebSocket dial: failed 
```

**To Reproduce**
1. Run `boundary authenticate  ...`
2. Run `boundary connect ssh ...`
3. See error

**Expected behavior**
The command should connect and create a valid SSH session via the worker proxy node. 

**Additional context**
I recently upgraded boundary from an earlier version.  All other worker nodes are working and were upgraded at the same time.  The configurations on all worker nodes are the same except for the `public_addr` fields.  Uninstalling/purging/reinstalling boundary did not resolve the issue on the troublesome node.

boundary-controller.hcl:
```
controller {
  name = "boundary controller"
  description = "boundary controller"
  database {
    url = "postgresql://x:x@localhost:5432/boundary"
  }
}

listener "tcp" {
  address = "10.1.20.137"
  purpose = "api"
  tls_disable = true

}

# Data-plane listener configuration block (used for worker coordination)
listener "tcp" {
  address = "10.1.20.137"
  purpose = "cluster"
  tls_disable = true
}


kms "transit" {
  purpose            = "root"
  address            = "https://xxxxxxxxxx:8200"
  token              = "s.xxxxxxxxxx"
  disable_renewal    = false

  // Key configuration
  key_name           = "root"
  mount_path         = "transit/"

  // TLS Configuration
  tls_skip_verify    = false
}

kms "transit" {
  purpose            = "worker-auth"
  address            = "https://xxxxxxxxxxxxxx:8200"
  token              = "s.xxxxxxxxxx"
  disable_renewal    = false

  // Key configuration
  key_name           = "worker-auth"
  mount_path         = "transit/"

  // TLS Configuration
  tls_skip_verify    = false
}
```

boundary-worker.hcl:
```
worker {
  name = "boundary worker 01"
  description = "boundary worker"
  controllers = [
    "10.1.20.137"
  ]

 public_addr = "54.x.x.x"

}

listener "tcp" {
  address = "10.1.0.104"
  purpose = "proxy"

  tls_disable = true
}

kms "transit" {
  purpose            = "worker-auth"
  address            = "https://example.com:8200"
  token              = "s.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  disable_renewal    = "false"

  // Key configuration
  key_name           = "worker-auth"
  mount_path         = "transit/"

  // TLS Configuration
  tls_skip_verify    = false
}
```

**Comment by jefferai** [comment]
I tried responding to the Discuss item but it said it had been deleted :-)

Assuming that there are no errors in the worker or controller events, my guess is that something else, not the worker, is receiving the actual network connection, and that either that intermediary configuration is different, or that intermediary is only affecting that worker address. Do you have an ELB or something between the clients and the worker nodes?

**Comment by evanravenelle** [comment]
@jefferai The Discuss post was flagged by the spam bot, it says it's waiting for the post to be reviewed.  In any case, the workers in question are EC2 instances exposed publicly via EIP in a public subnet in my Boundary VPC, and I am hitting the public IP directly.  It works on all other nodes but this one.

**Comment by jefferai** [comment]
Do the logs for that worker say anything? The only thing I can think of other than it actually being terminated by some middleware is that the worker is not actually successfully maintaining a connection with controllers and as a result is unable to validate the incoming client certificate. In that case I'd expect that errors would be getting logged by the worker.

**Comment by evanravenelle** [comment]
I would tend to agree and indeed there are no log messages relating to failures on the worker, so to test I moved the EIP to another known working boundary worker and updated that worker's configuration to use the new `public_addr` value.

Moving the EIP to the new worker allowed connections to complete successfully using the same public IP and configuration as the node returning `bad certificate`. I then moved the EIP back to the "bad" node and received the same `bad certificate` error message as previously from that node.  Finally I moved the EIP back to the new node and was once again able to connect successfully. All workers are in the same VPC and share a security group so it would seem it's something about that specific host that is the problem.

I am content to no longer head down this rabbit hole since it's now working for me on another known worker with the same IP but if you'd like me to gather more information from the failing host to see where the problem might be occurring, I can certainly do so.

**Comment by jefferai** [comment]
I'd certainly be curious but at the same time am not really sure what to ask you to gather. :-/

One thing that might be interesting would be to deploy an additional worker and see if that worker behaves. I have actually seen strange behavior on a single box that is due to underlying hardware issues at the cloud provider so it's not impossible that it is truly the box and not the software that is behind it. (This actually happened: a customer was setting up 7 Vault replication secondaries and the seventh they set up with the same exact configuration as the first six was behaving strangely. After a lot of trying to figure out what was going on, they deployed and 8th and 9th and both were totally fine. At that point they could only conclude that it was related to the hardware the 7th node was physically running on). Being able to successfully deploy another worker would possibly provide some reassurance that it really is limited to just that one host.

**Comment by evanravenelle** [comment]
I think I'm in a similar situation here.  The worker I moved the EIP to was set up using the same terraform code and running the same configuration, and was built _after_ the worker in question failed.  Thanks for the help and the sanity check!

**Comment by jefferai** [comment]
Oh nice!

We have a little bit of leeway in the certificates -- I think about 30 seconds -- but if it's more than that there could indeed be failures!
