### ISSUE TITLE
TCP Reset after few seconds

### ISSUE THREAD

**Issue by giulio1979** [hashicorp/boundary#1816]
Hi, I have been experiencing a lot of TCP resets after establishing a connection. Is this normal behaviour ?

**To Reproduce**
1. Run `boundary authenticate  ...`
2. Run `boundary connect ...`
3. Establish a connection to a database via the boundary tunnel (eg postgres via a simple tunnel on port 5432)
4. Sit idle 30s
5. Attempt to execute a query results in error as the session has been reset

**Expected behavior**
Session would stay active for a period of time (configurable timeout?)

**Additional context**
Boundary 0.7.3
Number of sessions on worker: 1

**Comment by jefferai** [comment]
I don't see this behavior:

```
$ time psql postgres://postgres:password@localhost:41063/boundary?sslmode=disable
psql (12.9 (Ubuntu 12.9-0ubuntu0.20.04.1), server 11.12 (Debian 11.12-1.pgdg90+1))
Type "help" for help.

boundary=# \dt
boundary=# exit

real    2m26.354s
user    0m0.045s
sys     0m0.000s
```
I let it sit for about 2.5 minutes after doing a `\dt` and it stayed connected. Is your target maximum connection time set to 30 seconds?

**Comment by giulio1979** [comment]
As far as I know I dont have connection limits set but I might be impacted by other bugs unfortunately on my installation, especially the db deadlocks. I think we should close and I will reopen after the deadlocks are sorted if problem still occurs

**Comment by jefferai** [comment]
Ah, I can imagine DB deadlocks having a hand here. I'll close, feel free to reopen after that's sorted!
