### ISSUE TITLE
ARM64 Container Image Location

### ISSUE THREAD

**Issue by mister2d** [hashicorp/boundary#1830]
I can see that an arm container image is produced, but where is it published? Only the `linux/amd64` build is present in the public Docker registry.

**Comment by Shanduur** [comment]
If I understand the repository correctly, the `arm64` images are not built by the CI, thus they are not published. As you can see in the [Makefile (Line 247)](https://github.com/hashicorp/boundary/blob/86245c48da984a5034e735d41ba843466209ffde/Makefile#L247) you can build the image by yourself.

**Comment by mdeggies** [comment]
👋  Hey there! We recently started building docker images for all linux variants on merges to main / to the release branches. In the next Boundary release, arm images will be published to Dockerhub. Here is where the docker builds are configured in CI: https://github.com/hashicorp/boundary/blob/main/.github/workflows/build.yml#L285-L321

**Comment by mister2d** [comment]
Thank you. This is much appreciated!
