### ISSUE TITLE
listen-port not working on cli client

### ISSUE THREAD

**Issue by andybaran** [hashicorp/boundary#1834]
**Describe the bug**
When using the OS X cli client and specifying a `listen-port` the proxy does not come up on the specified port. Testing has shown this to occur whether the `default-port` flag is also used or not. 

**To Reproduce**
1. Run `export BOUNDARY_ADDR="http://ip_address:9200/"`
2. Run `boundary authenticate  ...`
2. Run `boundary connect -tls-insecure -target-id <target-id> tcp -listen-port 50445

```
Proxy listening information:
  Address:             127.0.0.1
  Connection Limit:    -1
  Expiration:          Fri, 28 Jan 2022 20:43:04 EST
  Port:                51014
  Protocol:            tcp
  Session ID:          s_SvbTfXauwv
```
**Expected behavior**
Proxy to be available on port specified with `-listen-port` flag.

**Additional context**

- OS X = 11.6.1
- Boundary client version = 
```
Version information:
  Git Revision:        221acff4cc4d1f9be7619a657274c043999e62cc
  Version Number:      0.7.4
```

**Comment by louisruch** [comment]
Hey @andybaran I am not sure what is going on here, I can confirm this is working as expected on my mac:

```
./boundary connect -tls-insecure -target-id ttcp_1234567890 -listen-port 50445

Proxy listening information:
  Address:             127.0.0.1
  Connection Limit:    -1
  Expiration:          Mon, 31 Jan 2022 07:14:25 PST
  Port:                50445
  Protocol:            tcp
  Session ID:          s_3S3mG0ZTvv
```

Note I am using `./` because I wanted to make sure there was no issue with the released version and not my local dev boundary binary.

```
./boundary version

Version information:
  Git Revision:        221acff4cc4d1f9be7619a657274c043999e62cc
  Version Number:      0.7.4
```

Have you tried by just setting the EnvVar? 

```
$ export BOUNDARY_CONNECT_LISTEN_PORT=50445
$ boundary connect  -target-id ttcp_1234567890

Proxy listening information:
  Address:             127.0.0.1
  Connection Limit:    -1
  Expiration:          Mon, 31 Jan 2022 07:22:19 PST
  Port:                50445
  Protocol:            tcp
  Session ID:          s_lJG2zp7PWa
```
