### ISSUE TITLE
Not found errors on startup

### ISSUE THREAD

**Issue by jefferai** [hashicorp/boundary#1925]
On startup we currently get some events:

```
{
  "id": "Q9ZN6uQZoX",
  "source": "https://hashicorp.com/boundary/dev-controller/boundary-dev",
  "specversion": "1.0",
  "type": "error",
  "data": {
    "error": "db.LookupWhere: record not found, search issue: error #1100: dbw.LookupWhere: record not found",
    "error_fields": {
      "Code": 1100,
      "Msg": "",
      "Op": "db.LookupWhere",
      "Wrapped": {}
    },
    "id": "e_c6EmYVKTHg",
    "version": "v0.1",
    "op": "db.LookupWhere"
  },
  "datacontentype": "text/plain",
  "time": "2022-03-15T14:02:21.607812-07:00"
}
{
  "id": "3fS3pYOdAz",
  "source": "https://hashicorp.com/boundary/dev-controller/boundary-dev",
  "specversion": "1.0",
  "type": "error",
  "data": {
    "error": "db.LookupWhere: record not found, search issue: error #1100: dbw.LookupWhere: record not found",
    "error_fields": {
      "Code": 1100,
      "Msg": "",
      "Op": "db.LookupWhere",
      "Wrapped": {}
    },
    "id": "e_T9Pmiq92Ze",
    "version": "v0.1",
    "op": "db.LookupWhere"
  },
  "datacontentype": "text/plain",
  "time": "2022-03-15T14:02:22.472712-07:00"
} 
```

Putting a conversation here with light editing:

Irena:
It's happening when the Controller registers the AWS and Azure plugins. They aren't found, and end up being created (which is the expected behaviour). That code path is here:
https://github.com/hashicorp/boundary/blob/main/internal/cmd/base/initial_resources.go#L633
->
 https://github.com/hashicorp/boundary/blob/main/internal/plugin/host/repository_plugin.go#L115-L117
->
https://github.com/hashicorp/boundary/blob/main/internal/cmd/base/initial_resources.go#L638-L643

I looked into why we're emitting the LookupWhere error. When the lookup fails, we wrap the error, which ends up emitting the error:
https://github.com/hashicorp/boundary/blob/main/internal/db/read_writer.go#L468
->
https://github.com/hashicorp/boundary/blob/main/internal/db/read_writer.go#L516-L517
->
https://github.com/hashicorp/boundary/blob/main/internal/errors/error.go#L140-L155
->
https://github.com/hashicorp/boundary/blob/main/internal/errors/error.go#L111 (edited) 

The read_writer wrapError function ignores any incoming opts; had we passed the opts.withoutEvent opt this would not have been emitted

Jeff:
Ah so it's emitted even before we hit the error case in the calling function. Want to pull @jimlambrt into this. We could pass withoutEvent but I wonder if that's where we should be emitting it in the first place. Like, is it normal to want to do a lookup and have no records found be a perfectly acceptable success criteria

**Comment by jimlambrt** [comment]
I'm thinking that we should stop emitting error events for "not found" lookups/searches.
