### ISSUE TITLE
Giving access to targets to users rather than role.

### ISSUE THREAD

**Issue by swapnil-raj** [hashicorp/boundary#1927]
**Is your feature request related to a problem? Please describe.**
If i have to add a target which only one user is going to use then also i have to create a role and assign the target there. If only i had option to add targets to account this would'nt be a problem.

**Describe the solution you'd like**
As we add permission to roles so that users in that role can access targets, it would be nice if we can directly add targets to user account.

**Comment by xingluw** [comment]
Hi @swapnil-raj, we don't allow targets to be directly accessed by a "user", instead they need to be assigned a "role" first, to follow the [IAM](https://en.wikipedia.org/wiki/Identity_management) model. You can find out more in our [Domain Model](https://www.boundaryproject.io/docs/concepts/domain-model) documentation.
