### ISSUE TITLE
unable to configure oidc auth method if issuer doesn't match discovery document issuer.

### ISSUE THREAD

**Issue by jimlambrt** [hashicorp/boundary#1935]
Currently, boundary requires that the issuer used for discovery must match the issuer in the discovery document.   This is preventing some users from enabling an OIDC auth method ( [this user's discussion post about oracle's provider](https://discuss.hashicorp.com/t/integration-between-boundary-oidc-oracle-idcs/37259) ) .

We should consider supporting an option to skip the verification comparison of the issuer used for discovery against the issuer from the discovery doc.  This would require [cap](https://github.com/hashicorp/cap) changes and then subsequent boundary configuration changes (db, repo, api, and cli)

**Comment by PPacent** [comment]
Thanks for the suggestion, while we don't have a timeline for this improvement this will be added to our product backlog. In the meantime, we will keep this issue open so that it can receive upvotes from the community to inform its backlog priority.

**Comment by jimlambrt** [comment]
this was fixed.
