### ISSUE TITLE
Cannot reopen window of macOS desktop GUI

### ISSUE THREAD

**Issue by wokalski** [hashicorp/boundary#2006]
**Describe the bug**
You cannot reopen boundary on Mac after closing the window

**To Reproduce**
1. Launch boundary on macOS (running 11.2 (20D64))
2. Click the red close button
3. Click boundary icon to reopen the window

**Expected behavior**
The window opens again

**Additional context**
Currently the window never reopens. Can it be that it works on newer versions on macOS? I'm using boundary 1.4.2

**Comment by micchickenburger** [comment]
I have this issue, too.  I have to close boundary from the task bar and then reopen in order to see the UI again.

**Comment by calcaide** [comment]
Hey :wave:

We are investigating and working on this issue.

We will keep you posted on what version this will be fixed.

Thanks for reporting.

**Comment by calcaide** [comment]
@wokalski @micchickenburger

This issue was fix in the latest Desktop Client release version `1.4.3`.

Let us know if you still having any realted issues.

Thanks for reporting.
