### ISSUE TITLE
Failed to WebSocket dial use Boundary Cli with version  0.8.0

### ISSUE THREAD

**Issue by incubator4** [hashicorp/boundary#2062]
**Describe the bug**
After use brew upgrade `boundary` cli from version `0.7.6` to `0.8.0`, then got this error
```shell
$ boundary connect ssh -target-id <target> -username ops
Error dialing the worker: failed to WebSocket dial: failed to send handshake request: Get "http://<worker-address>:9202/v1/proxy": proxyconnect tcp: EOF
kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 53018
error fetching connection to send session teardown request to worker: Error dialing the worker: failed to WebSocket dial: failed to send handshake request: Get "http://<worker-address>:9202/v1/proxy": proxyconnect tcp: EOF
```

Then I uninstall brew tap boundary cli, and download the `0.7.6` binary file, then it work well

**To Reproduce**
1. Run `boundary authenticate  ...`
2. Run `boundary connect ssh -target-id <target> `
3. See error

**Comment by jefferai** [comment]
This may well be related to #2063 for which a fix is coming in 0.8.1 -- can I ask you to retry the upgrade when that is out?

**Comment by jefferai** [comment]
Time is a flat circle. 0.8.1 is out since last week :-D Can you try upgrading to it?

**Comment by jefferai** [comment]
I'm going to close this for now as there have been a number of fixes. Please report back if you still have issues with the latest version of Boundary. Thanks!
