### ISSUE TITLE
IGNORE

### ISSUE THREAD

**Issue by KT-1000** [hashicorp/boundary#2085]
**Is your feature request related to a problem? Please describe.**
Test for Jira integration.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by AleLuz01** [comment]
Test comment

**Comment by AleLuz01** [comment]
New comment
