### ISSUE TITLE
Boundary server should refuse to start when max_open_connections is < 5

### ISSUE THREAD

**Issue by johanbrandhorst** [hashicorp/boundary#2095]
**Describe the bug**
When running `boundary server` with `database.max_open_connections` set to `1`, the startup blocks forever.

**To Reproduce**
1. Create a configuration file with the database connection limit set to 1
2. Run `boundary server -config <your_config_file>`

**Expected behavior**
I expected `boundary` to error when `max_open_connections` is too low.

**Additional context**

Discovered while working on https://github.com/hashicorp/boundary/pull/2094

**Comment by johanbrandhorst** [comment]
I was informed that the minimum number of connections that Boundary requires is 5, as documented in our docs: https://www.boundaryproject.io/docs/configuration/controller#max_open_connections. We should detect that the number is too low and refuse to start instead of deadlocking though.

**Comment by Gabrielopesantos** [comment]
Hello, this seemed like an interesting issue (and easy) so I have decided to make a proposal solution to fix it.

**Comment by Gabrielopesantos** [comment]
Hey @johanbrandhorst, 
This project does not have any "good-first-issue" issues tagged, are there are non tagged "good-first-issues" that I could try to do?

Thanks in advance.
