### ISSUE TITLE
Generate nicer SDK getters

### ISSUE THREAD

**Issue by johanbrandhorst** [hashicorp/boundary#2122]
**Is your feature request related to a problem? Please describe.**
When using the SDK, the result getters all return `interface{}` when they have a concrete type available. This is a poor experience for the user. See https://github.com/hashicorp/boundary/blob/2a5aaea8b234425007255b3013d7d18b02128e70/api/sessions/session.gen.go#L45-L47 and https://github.com/hashicorp/boundary/blob/2a5aaea8b234425007255b3013d7d18b02128e70/api/sessions/session.gen.go#L74-L76 for examples.

**Describe the solution you'd like**
I would like the generated code to use typed returns.

**Additional context**
This was raised as a concern by internal users of our SDK. The template for this part of the generated SDK is here: https://github.com/hashicorp/boundary/blob/2a5aaea8b234425007255b3013d7d18b02128e70/internal/api/genapi/templates.go#L564-L631

**Comment by PPacent** [comment]
Thank you for raising this item @johanbrandhorst! We'll keep this item open to gauge interest from the community to inform its priority on our roadmap.

**Comment by jefferai** [comment]
Closing as #2238 has been merged
