### ISSUE TITLE
Session credentials were not accepted or session is unauthorized

### ISSUE THREAD

**Issue by waddles** [hashicorp/boundary#2257]
There seems to have been a breaking change in 0.8.0 that prevents connections with older boundary workers.

We have a boundary server and workers running 0.7.1 and use OIDC authentication. When I upgrade to boundary CLI version 0.8.0 or later it fails to connect to databases. Downgrading back to 0.7.6 succeeds.

```bash
❯ ./boundary version

Version information:
  Git Revision:        bc86b4e9e9adfdf07183cbf140a2802fb453b35f
  Version Number:      0.8.0

❯ ./boundary connect postgres -dbname confluencedb -target-name t_confluence_db_write -target-scope-name Corporate
Session credentials were not accepted, or session is unauthorized
psql: error: connection to server at "127.0.0.1", port 61130 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
error fetching connection to send session teardown request to worker: Session credentials were not accepted, or session is unauthorized
```

The above is actually a mix of messages from the different binaries. If I just use `boundary connect` and connect to the proxy with `psql` in a different terminal I see the error messages separately. Repeated attempts will cause boundary to output
```
Session credentials were not accepted, or session is unauthorized
Session credentials were not accepted, or session is unauthorized
^Cerror fetching connection to send session teardown request to worker: Session credentials were not accepted, or session is unauthorized
```

This seems very similar to #2062 but I have tried 0.8.1 and 0.9.1 and the problem has not been fixed yet.

**Comment by waddles** [comment]
We did the obvious and upgraded our server and db schema to 0.9.1. Now everything works fine with 0.9.1 CLI, but 0.8.0 CLI just seg faults.

**Comment by xingluw** [comment]
Hi @waddles, are you having any issues using 0.9.1 controllers and workers and CLI? If not, I can close this thread.

**Comment by waddles** [comment]
No issues as long as all parts are upgraded to the same version. Maintaining backwards compatibility should be a goal for your project as it matures though. Nobody wants to upgrade everything at once, find an issue, then downgrade everything back again.
