### ISSUE TITLE
Boundary Ignoring execution_dir

### ISSUE THREAD

**Issue by TaysirTayyab** [hashicorp/boundary#2284]
**Describe the bug**
Bug was initially described here: https://discuss.hashicorp.com/t/latest-boundary-versions-ignoring-plugins-execution-dir/41281

In short, boundary does not appear to respect the `plugins.execution_dir` configuration in 0.8.0+. On that thread, developers claimed that the issue would be fixed in 0.9.1. I gave it a try to day and am experiencing the same behavior.

**To Reproduce**
1. Create folder `/var/run/boundary/plugin-exec` with appropriate permissions.
2. Change the `execution_dir` in the boundary config.
    ```
    plugin_dir {
      execution_dir = "/var/run/boundary/plugin-exec"
    }
    ```
3. Running boundary still shows error trying to use `/tmp`

```
$ /usr/bin/boundary server -config /etc/boundary-controller.hcl
Error parsing KMS configuration: error fetching kms plugin rpc client: fork/exec /tmp/205944216/boundary-plugin-kms-awskms.gz: permission denied
```

**Expected behavior**
KMS plugin should run in the correct directory. Works correctly in 0.7.6.

**Additional context**
This is necessary since we use hardened images where nothing can be executed out of `/tmp`.

**Comment by TaysirTayyab** [comment]
Whoops, I was running on 0.9.0 on the wrong server. Please disregard this. I made sure I was on the right version this time and the KMS plugin was working as expected.

Please close this issue. My fault for the confusion.

**Comment by johanbrandhorst** [comment]
Thanks for reporting back, glad to hear it worked itself out!
