### ISSUE TITLE
0.9.1 Fails to start with multiple AWS key definitions.

### ISSUE THREAD

**Issue by TaysirTayyab** [hashicorp/boundary#2343]
**Describe the bug**
Same issue as #2340, but on AWS. Quick summary is that defining multiple AWS keys on 0.9.1 causes server start to fail.

**To Reproduce**
Using the following config (sanitized), attempting to start the server with `boundary -config ./controller.hcl` fails with error:

```
Error parsing KMS configuration: error writing out plugin for execution: open /var/run/boundary/plugin-exec/boundary-plugin-kms-awskms.gz: text file busy
```

Issue is resolved when removing the extra key defintions for worker-auth and recovery. Again exactly the same reproduce as #2340.

Here's the config:

```
disable_mlock = true

plugins {
	execution_dir = "/var/run/boundary/plugin-exec"
}

telemetry {
  prometheus_retention_time = "24h"
  disable_hostname          = true
}

controller {
  name        = "demo-controller-1"
  description = "A controller for a demo!"

  database {
    url = "postgresql://boundary:<sanitized>@<sanitized>:5432/boundary"
  }
}

listener "tcp" {
	address                           = "10.249.124.47:9200"
	purpose                           = "api"
	tls_disable                       = true
	cors_enabled                      = true
	cors_allowed_origins              = ["*"]
}

listener "tcp" {
	address                           = "10.249.124.47:9201"
	purpose                           = "cluster"
	tls_disable                       = true

kms "awskms" {
	purpose    = "root"
	key_id     = "global_root"
        kms_key_id = "<sanitized>"
}

kms "awskms" {
	purpose    = "worker-auth"
	key_id     = "global_worker_auth"
        kms_key_id = "<sanitized>"
}

kms "awskms" {
	purpose    = "recovery"
	key_id     = "global_recovery"
        kms_key_id = "<sanitized>"
}
```

**Expected behavior**
Server should start correctly.

**Additional context**
None.

**Comment by jefferai** [comment]
Just a note as a workaround until 0.10.1 comes out: if you remove the plugin execution dir and let boundary create temporary directories it should work. The reason is that it will then create a temp dir per plugin instantiation, instead of using the same execution dir for each execution of a plugin.
