### ISSUE TITLE
0.9.0 Boundary OIDC managed group filtering does not "work" from UI

### ISSUE THREAD

**Issue by Anton-Sagurov** [hashicorp/boundary#2345]
**Describe the bug**
The OIDC managed-group Filter does not allow [described](https://www.boundaryproject.io/docs/concepts/filtering/oidc-managed-groups#examples) filtering rules:
![image](https://user-images.githubusercontent.com/93559109/183879442-7b5ac6c6-4475-4c15-86ee-acf290b2d13a.png)

**To Reproduce**
1. Setup OIDC Auth Method.
2. Try to create managed-group with filter from Boundary UI.
3. See error

**Expected behavior**
1. The managed-group filter works as described in the example [documentation]https://www.boundaryproject.io/docs/concepts/filtering/oidc-managed-groups#examples.

**Additional context**
The controller log:
```json
{"id":"5eTQQrL5K8","source":"https://hashicorp.com/boundary/boundary-controller-7c946f9d46-85gjq/controller","specversion":"1.0","type":"observation","data":{"latency-ms":0.915374,"request_info":{"id":"gtraceid_zGfwmLsHcSr18sZ44Qen","method":"POST","path":"/v1/managed-groups","public_id":"at_bVX6IbQIf9","client_ip":"10.13.0.246"},"start":"2022-08-10T10:30:56.98672729Z","status":400,"stop":"2022-08-10T10:30:56.987642664Z","version":"v0.1"},"datacontentype":"application/cloudevents","time":"2022-08-10T10:30:56.987659914Z"}
````

**Comment by randallmorey** [comment]
Resolved by hashicorp/boundary-ui#1238
