### ISSUE TITLE
SSH Target Type - Unknown type provided

### ISSUE THREAD

**Issue by thanks4wifi** [hashicorp/boundary#2392]
**Describe the bug**

Attempting to use the CLI to create a `ssh` target results in an error.

**To Reproduce**

1. Authenticate to boundary
2. Run `boundary targets create ssh -default-port=22 -session-connection-limit=-1 -session-max-seconds=600 -name=test1 -scope-id=p_SOME_ID_HERE`
3. See error

```
Error from controller when performing create on ssh-type target

Error information:
  Kind:                InvalidArgument
  Message:             Error in provided request.
  Status:              400
  context:             Error from controller when performing create on ssh-type target

  Field-specific Errors:
    Name:              -type
      Error:           Unknown type provided.
```

**Expected behavior**

Command executed without an error.

**Additional context**

n/a

**Comment by louisruch** [comment]
Hi @thanks4wifi 
Are you trying this on HCP [beta](https://cloud.hashicorp.com/products/boundary) or the OSS binary? The `ssh` target is only valid against HCP currently.

**Comment by thanks4wifi** [comment]
I was using the OSS binary.

**Comment by louisruch** [comment]
Ill close this Issue for now, please feel free to reach out if you experience any issue around `ssh` targets against HCP
