### ISSUE TITLE
invalid ciphertext: no prefix using vault kms

### ISSUE THREAD

**Issue by dagtveit** [hashicorp/boundary#2403]
<!-- Please reserve GitHub issues for bug reports and feature requests.

For questions, the best place to get answers is on our [discussion forum](https://discuss.hashicorp.com/c/boundary), as they will get more visibility from experienced users than the issue tracker.

When trying to use recovery key to create resources it fails with invalid ciphhertext. it looks like the prefix is missing and vault seems to require this, also the error from the cli seems wrong.

boundary cli response:
Error from controller when performing create on scope

Error information:
  Kind:                Unauthenticated
  Message:             Unauthenticated, or invalid token.
  Status:              401
  context:             Error from controller when performing create on scope

boundary log:
error","data":{"error":"error decrypting recovery info: rpc error: code = Unknown desc = Error making API request.\n\nURL: PUT http://vault.vault.svc:8200/v1/boundary/decrypt/recovery\nCode: 400. Errors:\n\n* invalid ciphertext: no prefix","error_fields":{},"id":"e_StBhNOTbD8","version":"v0.1","op":"auth.(verifier).decryptToken","request_info":{"id":"gtraceid_aKhvL1Ww7TTX8q4zE1Xj","method":"POST","path":"/v1/scopes","client_ip":"127.0.0.1"},"info":{"msg":"decrypt recovery token: error parsing and validating recovery token"}},"datacontentype":"application/cloudevents","time":"2022-08-29T10:52:10.611988452Z"}

vault audit log:

,"error":"1 error occurred:\n\t* invalid request\n\n"}

**Comment by hsimon-hashicorp** [comment]
Hi there - Can you please fill out some more information in this issue? The scenario where you're seeing the error, as well as your configuration. Thanks!
