### ISSUE TITLE
Doc error: Wrong env var

### ISSUE THREAD

**Issue by stephan242** [hashicorp/boundary#2546]
**Describe the bug**
https://learn.hashicorp.com/tutorials/boundary/hcp-manage-intro?in=boundary/hcp-administration

This page mentions `AUTH_METHOD_ID`, while apparently it's supposed to be `BOUNDARY_AUTH_METHOD_ID`.

**To Reproduce**
```
$ echo $AUTH_METHOD_ID
ampw_XXXX
$ echo $BOUNDARY_AUTH_METHOD_ID
ampw_XXXX
$ boundary accounts list

Account information:
[...]
$ unset BOUNDARY_AUTH_METHOD_ID
$ boundary accounts list
AuthMethod ID must be passed in via -auth-method-id or BOUNDARY_AUTH_METHOD_ID
```

**Expected behavior**

**Additional context**

**Comment by stellarsquall** [comment]
thanks for reporting! 

There is a built-in `BOUNDARY_AUTH_METHOD_ID` variable that can be used with the CLI, however this tutorial collection consistently passes `AUTH_METHOD_ID` to all commands that require it, meaning the learner should have no issues following along.

We will update this for all tutorials eventually to create consistency, but this shouldn't be a bug.

**Comment by stellarsquall** [comment]
This is now fixed, thanks again!
