### ISSUE TITLE
OIDC managed groups do not display in role principals in the admin UI

### ISSUE THREAD

**Issue by Tristan971** [hashicorp/boundary#2650]
**Describe the bug**
Managed groups show up as role principals in the CLI but not in the admin UI's role principals tab

**To Reproduce**
1. Create a role
2. Set a managed group as one of the principals
3. Compare the cli's `role read` principals section, and the admin UI role principals tab

![2022-11-28 03_19_54](https://user-images.githubusercontent.com/875533/204184639-c836d163-8343-40bf-b2de-d6be869f7aa6.png)

**Expected behavior**
The role's principals list includes lines for its OIDC managed role principals

**Additional context**
N/A

**Comment by anando-chatterjee** [comment]
Hi @Tristan971 thanks for reporting this issue! We are aware of this discrepancy around the way managed groups are displayed in the CLI vs. the admin UI and plan on addressing it in a future release.

**Comment by reza-solaris** [comment]
Is this only at the admin UI, or does it actually affect the functionality as well?

**Comment by Tristan971** [comment]
Only admin UI; ie it's a visual bug

**Comment by reza-solaris** [comment]
Thanks, @Tristan971

**Comment by xingluw** [comment]
Hi @Tristan971, this bug has been fixed in Boundary 0.12 (rollout is starting today so it may take a few days for you to receive it)

**Comment by Tristan971** [comment]
Great, thanks! 🙂
