### ISSUE TITLE
Have a search bar on the desktop app or webUI to make it easier to search targets

### ISSUE THREAD

**Issue by maireanu** [hashicorp/boundary#2780]
Have a search bar on the desktop app or webUI to make it easier to search targets.
It is hard to find the desired target when having a big number of targets

**Comment by xingluw** [comment]
Hi @maireanu, this is a good idea and something we are planning to implement in the future, I will leave this request open for community upvotes

**Comment by lals1** [comment]
Given the thousands of nodes planned to be added to Boundary in our case, this is a must-needed feature. Any update on the implementation timeline?

**Comment by anando-chatterjee** [comment]
Hi @maireanu @lals1 - we are currently conducting a bunch of discovery on this topic and would like to learn more about use cases and scenarios where search/filtering could make the Boundary UX better. If you are interested in chatting about this topic for ~30 mins, could you please shoot me an email at anando[AT]hashicorp[DOT]com with your availability? Thanks and look forward to hearing from you!

**Comment by anando-chatterjee** [comment]
Another call for volunteers who'd like to share their feedback and perspectives on search and discoverability within Boundary - **please sign up using [this link](https://app.respondent.io/respondents/v2/projects/view/64ac552e114be4f3f0a4704f/seeking-boundary-admins-and-end-users?invite=0f67478a-eae4-48cb-8a35-a2c36dc878e7)**. There is a $50 reward as a way for us to thank you for your time should you get selected for a discovery call. Thanks and look forward to all the community feedback.

**Comment by schndr** [comment]
Hello, I completely concur with the statement [here](https://github.com/hashicorp/boundary/issues/2780#issuecomment-1521811939), it's a must-needed feature. It would be incredibly useful to have a feature that enables searching through the attached resource tags of the provider, in addition to a simple search function. For instance, AWS RDS instance tags are accessible through the Boundary UI and such a feature would greatly enhance the user experience.

**Comment by anando-chatterjee** [comment]
@schndr are you open to having a quick call so that we are able to learn a little more about your Boundary use and how search/filtering could help you? If so, please drop me an email (I have posted it in the thread above). Look forward to hearing from you!

**Comment by schndr** [comment]
Hey @anando-chatterjee,

Do you have an update on this?

I sent an email in August without a reply. I also added myself to the Respondents.io project `Seeking HashiCorp Boundary admins and end-users`. Project description:

```
Struggling with search within HashiCorp Boundary? We'd love to talk with you about your current struggles and want to understand how we can make your experience better.
```

**Comment by anando-chatterjee** [comment]
Boundary 0.15 includes new search and filtering capabilities within the Desktop Client and the CLI. Users now have the ability to locate targets and sessions by simply typing in the partial or full name or ID of the target that they are trying to connect to. Additionally, they can further narrow down the results by filtering out the scopes or session states (active, pending, or terminated). Larger result sets are paginated for improved search performance. We will also support search and filtering within Boundary's admin web GUI in a subsequent release.

Please take a peek at other exciting additions to Boundary within the latest release by reviewing [this blog post](https://www.hashicorp.com/blog/boundary-0-15-adds-new-storage-policies-and-desktop-cli-features). As always, we would really appreciate this community's feedback on any of the new feature announcements. Thank you!
