### ISSUE TITLE
GPG Key Mismatch when Installing from Yum Repository

### ISSUE THREAD

**Issue by TaysirTayyab** [hashicorp/boundary#2833]
**Describe the bug**
When installing the Boundary from the Hashicorp Yum repo as described on [the install page](https://developer.hashicorp.com/boundary/tutorials/oss-getting-started/oss-getting-started-install), the install fails because the GPG key of the boundary packages does not match the key returned by  

**To Reproduce**
On a CentOS machine, follow the install instructions. Install fails.

**Expected behavior**
Application should install.

**Additional context**
Looks like you guys updated the repo GPG key recently, but the packages are signed with the old key. Just my two cents since I see the key expires 2023-1-10. Anyway here's more info.

Yum indicates the GPG signing key returned from https://rpm.releases.hashicorp.com/gpg does not match the package. This can  be verified by manually retrieving the key and inspecting it against the key of the package.

```
$ sudo yum install -y boundary
...
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/hashicorp/packages/boundary-0.11.2-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 69c085e9: NOKEY============ ]  25 MB/s | 102 MB  00:00:00 ETA
Public key for boundary-0.11.2-1.x86_64.rpm is not installed
boundary-0.11.2-1.x86_64.rpm                                                                                                                                    | 104 MB  00:00:03
Retrieving key from https://rpm.releases.hashicorp.com/gpg


The GPG keys listed for the "Hashicorp Stable - x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: boundary-0.11.2-1.x86_64
 GPG Keys are configured as: https://rpm.releases.hashicorp.com/gpg
```

Compare the package key ID `69c085e9` to the GPG key id `A621E701` for the repo.

```
$ curl https://rpm.releases.hashicorp.com/gpg | gpg
...
pub  4096R/A621E701 2023-01-10 HashiCorp Security (HashiCorp Package Signing) <security+packaging@hashicorp.com>
sub  4096R/69C085E9 2023-01-10 [expires: 2028-01-09]

**Comment by TaysirTayyab** [comment]
FYI the workaround is to use `--nogpgcheck`. So `yum install --nogpgcheck boundary`.

**Comment by johanbrandhorst** [comment]
Thanks for your report, this is being tracked here: https://status.hashicorp.com/incidents/5zxyf7fyzq91
