### ISSUE TITLE
outdated workers list

### ISSUE THREAD

**Issue by yongzhang** [hashicorp/boundary#2986]
**Describe the bug**
When scaling in workers, the list in Org>Workers will not be updated.

**To Reproduce**
1. Run an ASG with 4 workers.
2. Scale number of ASG to 1.
3. I can still see 4 workers in the list:
![image](https://user-images.githubusercontent.com/15604715/219565555-b7963597-9b03-4c96-8098-90bb828560a2.png)

**Expected behavior**
Workers list should be updated?

**Additional context**
Boundary version v0.12.0.
Controller and worker role are enabled in the same instance.

I use multil-answer DNS record for `initial_upstreams` in workers config (provided by AWS Cloud Map)
```
initial_upstreams = ["cluster.boundary.io"]
```
And I can confirm the dns has been correctly updated after ASG scaled in:

```
ubuntu@ip-10-130-251-65:~$ nslookup cluster.boundary.io
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   cluster.boundary.io
Address: 10.130.251.65
```

**Comment by xingluw** [comment]
Hi @yongzhang, Boundary will retain memory of all registered workers, but if you want to remove them, you can do it through the UI or the CLI by selecting the worker.

**Comment by yongzhang** [comment]
> Hi @yongzhang, Boundary will retain memory of all registered workers, but if you want to remove them, you can do it through the UI or the CLI by selecting the worker.

hmm, ok, if this is by design, do you think it’s better to remove dead workers automatically? In my case, it’s pointless to list terminated workers I think.

**Comment by xingluw** [comment]
This is to keep a record for the admin of all of the workers. For example, if a worker has disconnected unintentionally, the admin would know about its existence and when it was last seen.
