### ISSUE TITLE
"certificate is not standards compliant" on Mac with custom CA

### ISSUE THREAD

**Issue by t-botz** [hashicorp/boundary#2988]
My controller has a certificate issued by an AWS Private Certificate Authority. When running any command it fails with:

```shell
$ BOUNDARY_ADDR=https://<mydomain>:9200  boundary oidc -auth-method-id <XYZ>
Error trying to perform authentication start: error performing client request during Authenticate call: Post "https://<mydomain>:9200/v1/auth-methods/<XYZ>:authenticate": x509: “<mydomain>” certificate is not standards compliant
```

**Context**
Boundary version: 0.9+ (0.8.1 is fine, `0.9.0`/`0.10.0`/`0.11.0`/`0.12.0` are all failing)
System: M2 Mac (arm64 builds)

The machine is configured to trust the certificate, curl/browser/openssl are all ok with the cert.

**Potential cause**

This is extremely likely to be due to https://github.com/golang/go/issues/51991, when [boundary went onto `go 1.18`](https://github.com/hashicorp/boundary/compare/v0.8.1...v0.9.0#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R23)

**Comment by omkensey** [comment]
There are some rules Apple has in their default system policy (that golang leverages) for what certs are considered standards-compliant.  The [last substantive comment](https://github.com/golang/go/issues/51991#issuecomment-1431990039) in golang/go#51991 looks pretty comprehensive as to why it happens and potential workarounds.

Can you paste the cert here?

**Comment by t-botz** [comment]
Restarting didn't work for me.
Chrome is fine but I just realized Safari wasn't which kind of confirm its more a Mac issue than a Go/Boundary one.
I'll close the issue
