### ISSUE TITLE
Getting "vault secret is empty, integrity violation" error

### ISSUE THREAD

**Issue by japneet-sahni** [hashicorp/boundary#3012]
**Describe the bug**
I have created some team specific host sets/targets and using managed groups to give permissions to these static targets. I have started using dynamic credential libraries `openldap/static-cred/{{.User.Name}}.dc` for openldap secret engine of Vault. When I try to connect a host from Boundary, I get below error 

![image](https://user-images.githubusercontent.com/10338163/220978529-bbb2ab78-d102-4747-b4c4-acb5a1c02dc0.png)

**To Reproduce**
**Context:**
**_Boundary user details:_**
Name : princewillu
Snapshot from Boundary UI below

![image](https://user-images.githubusercontent.com/10338163/220980108-b1f61f92-feba-4dc4-bd09-3823a1f87660.png)

**_Vault openldap static role:_**
openldap/static-role/princewillu.dc

1. Login to Production Boundary Desktop Application using Azure AD.
2. Select the team specific target which you are authorized to (this target has a dynamic credential library)
3. Click on hosts and click connect on any host.
4. You will get above error as mentioned in description
5. Select a user-specific target which has a user-specific credential library (eg: `openldap/static-cred/princewillu.dc` )
6. This target works somehow.

> {"id":"kvvNG2t7UT","source":"https://hashicorp.com/boundary/boundary-controller-56fb79dcc5-49jct/controller","specversion":"1.0","type":"error","data":{"error":"targets.(Service).AuthorizeSession: vault.(Repository).Issue: vault secret is empty, integrity violation: error #3015","error_fields":{"Code":3015,"Msg":"","Op":"targets.(Service).AuthorizeSession","Wrapped":{"Code":3015,"Msg":"","Op":"vault.(Repository).Issue","Wrapped":null}},"id":"e_83GgCkXrE6","version":"v0.1","op":"targets.(Service).AuthorizeSession","request_info":{"id":"gtraceid_DRds40BElnpt82smCHCn","method":"POST","path":"/v1/targets/ttcp_2wsMmJTOcX:authorize-session","public_id":"at_XmL9QUc32q","client_ip":"10.151.236.6"}},"datacontentype":"application/cloudevents","time":"2023-02-22T17:49:56.129515947Z"}

**Expected behavior**
The team specific target should work for a user if he is part of the managed group. Unfortunately, user-specific target works perfectly fine, but team-specific target doesn't work. Saw these error codes https://github.com/hashicorp/boundary/blob/48e4fcce252c16f95cf3813c9f231e3f1e22e802/internal/errors/code.go#L123 and feels like 3014 makes more sense if a static role is not existing in vault but somehow I am unable to figure out the reason for 3015 error code.

**Additional context**
The weird problem is that somehow both team-specific and user-specific targets work on my sandbox boundary environment but doesn't work on production and thus blocking us from production rollout. I was even able to reproduce 3014 error on sandbox if I delete the static role on sandbox vault environment. 

Boundary Version on both sandbox and production: 0.11.2
Vault Version on both sandbox and production: 1.11.6

@jefferai @PPacent : For your visibility.

**Comment by PPacent** [comment]
Hi @japneet-sahni, this seems to be an issue the call Boundary is making to Vault to retrieve the credential. Can you confirm that you're able to check out a service account using the ldap role when interacting directly with Vault?

`vault write -f openldap/static-cred/princewillu.dc`

**Comment by japneet-sahni** [comment]
@PPacent : The user specific target is using the user specific credential library with exactly same vault path which is `openldap/static-cred/princewillu.dc` as shown in below snapshots. As stated earlier, the user is able to connect to such a host perfectly (which proves that vault write command would work fine, unfortunately, I won't be able to run it as I am not an admin for vault production environment). It's just that when he tries to access a team target with a dynamic credential library, he gets the "vault secret empty error" which ideally is the same vault path.

![image](https://user-images.githubusercontent.com/10338163/221273636-6a1e9434-45b2-468e-a75f-d58cb350f2df.png)
![image](https://user-images.githubusercontent.com/10338163/221273695-c59b55a6-db5e-4248-9693-005834be8a4f.png)
![image](https://user-images.githubusercontent.com/10338163/221273740-73fa8f46-377c-4ff8-a5de-eb88880e9ef7.png)

Let me know if you need more information. Also, I am unable to replicate this on sandbox, facing this issue only on production somehow.

**Comment by PPacent** [comment]
Hi @japneet-sahni, given that the templating works in your sandbox environment, we'd like to rule out that the issue isn't due to configuration. 

Are you collecting events from your environment? 

If [event logging](https://developer.hashicorp.com/boundary/tutorials/oss-configuration/event-logging) has been setup in the environment:

- Events can be found at the controller logs location setup in the events stanza of your controller’s configuration file (typically controller.hcl)

If event filtering has not been setup

- controller logs will be available at stdout (with errors going to stderr).
- You could collect them using a command on the controller like: `sudo journalctl -u <boundary-controller-process-name> --lines=50 --follow` after the issue has occurred. 

What we need to know is the Vault path Boundary is trying to access when user `princewillu` tries to connect to the team target. You may need to use `audit_filter_overrides` for `sensitive` to ensure the path is viewable in events.

**Comment by PPacent** [comment]
@japneet-sahni after you collect the logs, you can send them to our team for review at the following url.

URL : https://support-uploads.hashicorp.com/u/randeep
Email to enter : randeep at [the company that created Boundary] .com

**Comment by johanbrandhorst** [comment]
This turned out to be a result of an old controller version.
