### ISSUE TITLE
AWS KMS key sharing between cross-account controllers and workers

### ISSUE THREAD

**Issue by rhapsody008** [hashicorp/boundary#3030]
**Is your feature request related to a problem? Please describe.**
We are trying to deploy boundary controllers and workers across different AWS accounts, and utilize AWS KMS for key management. 
However we found that the following instructions https://www.boundaryproject.io/docs/configuration/kms/awskms only allows us to specify kms key id, not KMS ARN, so boundary controller/worker will only lookup kms key in the same AWS account it is running.

**Describe the solution you'd like**
We would like to seek a way for cross-account AWS kms key sharing between boundary controllers and workers (e.g. KMS ARN specification in boundary controller/worker configuration file)

**Comment by macmiranda** [comment]
You can use ARN without any issues inside the `awskms` block

**Comment by rhapsody008** [comment]
Hi @macmiranda may I know which field shall I configure the kms arn in? is in in the same field "kms_key_id" or a different parameter? thanks!

**Comment by rhapsody008** [comment]
@macmiranda thanks for the reply, it works!
