### ISSUE TITLE
Upgrading to `0.12.0` brakes connection to workers behind AWS NLB

### ISSUE THREAD

**Issue by madianas21** [hashicorp/boundary#3056]
**Describe the bug**
After upgrading our Boundary cluster from version `0.11.2` to version `0.12.0`, connections erroring out with ` server closed the connection unexpectedly` in pgAdmin4 and `no tofu token but not in correct session state` errors in Boundary workers.

Relevant parts of Boundary Worker logs:
```

1. pod: "boundary-worker-1" : {"connection_id":"sc_D8zk6zHJSr","msg":"connection successfully authorized","session_id":"s_hwOqxxOyO3"}
2. pod: "boundary-worker-1" : {"msg":"session successfully activated","session_id":"s_hwOqxxOyO3"}
3. pod: "boundary-worker-1" : {"connection_id":"sc_D8zk6zHJSr","msg":"connection closed","session_id":"s_hwOqxxOyO3"}
4. pod: "boundary-worker-0" : {"error":"no tofu token but not in correct session state","error_fields":{},"id":"e_9ln52LRbZM","version":"v0.1","op":"worker.(Worker).handleProxy","info":{"session_id":"s_hwOqxxOyO3"}}
5. pod: "boundary-worker-2" : {"error":"no tofu token but not in correct session state","error_fields":{},"id":"e_v9Bj5hHuTH","version":"v0.1","op":"worker.(Worker).handleProxy","info":{"session_id":"s_hwOqxxOyO3"}}
6. pod: "boundary-worker-1" : {"connection_id":"sc_cAX7tHZJGK","msg":"connection successfully authorized","session_id":"s_hwOqxxOyO3"}

```

As you can see the same session(`s_hwOqxxOyO3`), errors out when it gets routed to a different worker in the cluster.

#### About the setup
Boundary cluster with 3 controllers and 3 workers is deployed on AWS EKS. Workers are publicly exposed behind an AWS NLB. TCP port `9202` is open on an `ingress-nginx` and routes to a `ClusterIP` Kubernetes Service with three Boundary Worker Pods. Same for controllers, except the port is `9201`. This setup was working fine before the upgrade.

**To Reproduce**
1. Upgrade to version `0.12.0`
2. Connect via Boundary UI
3. Login via pgAdmin4
4. See error: `server closed the connection unexpectedly`
5. Login multiple times
6. Login successful
7. Open database
8. See error: `server closed the connection unexpectedly`

**Expected behavior**
If we downgrade back to version `0.11.2`, connections work fine without any issues.

**Additional context**
- Controller and Worker communicate via public TCP ingress connection, switching to an internal cluster network, did not solve the issue.
- We are not using the new `address` field in the Boundary Target.
- We are using the Worker Tag filters

**Comment by xingluw** [comment]
Hi @madianas21, Boundary workers don't need to be placed behind load balancers as the control plane will evenly distribute sessions across different workers that match the filter. You can increase/decrease the amount of workers you have deployed in order to meet the demand. For more information around high availability, see [here](https://developer.hashicorp.com/hcp/docs/boundary/self-managed-workers/size-self-managed-workers).

**Comment by macmiranda** [comment]
Hi @xingluw it's not so much the need of a load balancer but the convenience of using kubernetes ingress that made us choose this solution.
Nginx ingress takes care of the provisioning and configuration of the underlying NLB and we just need to configure the hostname that will be publicly accessible.
There is also a cost factor involved. Instead of using potentially 3 or more load balancers, one for each worker, we can reuse a single load balancer for all workers, given that they are in the same region.
I wouldn't be so certain that this is a bug if it weren't for the fact that this setup works perfectly fine with earlier versions.

**Comment by omkensey** [comment]
I would not have expected multiple workers behind a common NLB address to ever work -- ie. the current behavior you're seeing is what I would have expected all along, because of the way Boundary worker identity works.  The only way I could see it working then and not now is if you had client stickiness or multiple front-end addresses enabled on the NLB before and not currently -- but even that configuration is one that shouldn't be counted on (and wouldn't explain why reverting to 0.11.2 resumes the earlier behavior; maybe some difference in the behavior of 0.11.2 was causing your NLB to see only a single worker as healthy no matter how many there were and route all connections to it?  I'm honestly mystified.)

For distributing load between multiple workers, if you use HCP Boundary you can set up an "ingress" worker that other "egress" workers use as an upstream.  The ingress worker can either be an existing HCP-managed Boundary worker or it can be one you manage yourself.  If you self-manage the ingress worker, you can put an NLB in front of it if you wish, but that should generally not be needed.  Given multiple workers available for a given connection (e.g. multiple egress workers behind an ingress worker), Boundary will pick one at random to authorize the client to, so traffic will balance across them.

**Comment by madianas21** [comment]
Logs from Boundary workers with version `0.11.2` show that same session is being sent to different workers. Connections are being opened on different workers and closed correctly.
```
2023-03-07 12:53:42 boundary-worker-1 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_BZUtlAEENZ","msg":"connection successfully authorized"}
2023-03-07 12:53:42 boundary-worker-1 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_BZUtlAEENZ","msg":"connection closed"}
2023-03-07 12:53:55 boundary-worker-1 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_Un20cyM0Qd","msg":"connection successfully authorized"}
2023-03-07 12:53:55 boundary-worker-1 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_Un20cyM0Qd","msg":"connection successfully authorized"}
2023-03-07 12:54:19 boundary-worker-0 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_fRmAodYH4s","msg":"connection successfully authorized"}
2023-03-07 12:54:19 boundary-worker-2 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_qJYOtiNFq2","msg":"connection successfully authorized"}
2023-03-07 12:54:19 boundary-worker-2 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_qJYOtiNFq2","msg":"connection closed"}
2023-03-07 12:55:37 boundary-worker-0 {"session_id":"s_0iJaAqiMcG","connection_id":"sc_HGSxHFEaFZ","msg":"connection successfully authorized"}
```

AWS NLB  settings are: `Stickiness Off`, `Cross-zone load balancing Off`.
Kubernetes Service is of `type: ClusterIP` and  has `sessionAffinity: None`. Although, playing with these settings didn't fix the issue.

Asides from opened TCP port configuration on `ingress-nginx` there is no special setup for connection stickiness or routing: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-tcp
  namespace: ingress-nginx
data:
  '9202': boundary/boundary-worker:9202
```

This means that Boundary is somehow taking care of routing a connection to a worker that opened it.  
And yes, we are using AWS NLB with `ingress-nginx` for simplicity and cost considerations, for all of our services, which is a common scenario.

**Comment by macmiranda** [comment]
I'm pretty confident it has to do with this change:
https://github.com/hashicorp/boundary/pull/2795/files#diff-6ff5f74b004483502c801c331d42428f9bdd27b53e047299bf48f5cee7512a27L210-R217

The previous behavior was to query the controller for the `tofuToken` for an active session and now it uses the local token from the worker, which means that the other workers won't have access to the token anymore.

**Comment by macmiranda** [comment]
@jefferai @irenarindos

**Comment by irenarindos** [comment]
@macmiranda I've got a reversion of that line up in #3064 - I was wondering if you'd be willing to build Boundary from my PR branch and try to replicate your issue to see if it's resolved? Alternatively if you let me know what platform you need I can send a build to you.

Thanks so much!

**Comment by macmiranda** [comment]
Hi @irenarindos

I've built a few docker images for `linux/amd64` from your commits in https://github.com/hashicorp/boundary/pull/3064
If anyone wants to test them, they are available [here](https://hub.docker.com/r/macmiranda/boundary/tags)

The fix works for me:

client:
```
boundary=> \c boundary
psql (15.2, server 14.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
You are now connected to database "boundary" as user "v-token-to-boundary-wXwEgXFqE4g8IK5tK7fx-1678294339".
boundary=> \c boundary
psql (15.2, server 14.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
You are now connected to database "boundary" as user "v-token-to-boundary-wXwEgXFqE4g8IK5tK7fx-1678294339".
boundary=> \c postgres
psql (15.2, server 14.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
You are now connected to database "postgres" as user "v-token-to-boundary-wXwEgXFqE4g8IK5tK7fx-1678294339".
postgres=> \c boundary
psql (15.2, server 14.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
You are now connected to database "boundary" as user "v-token-to-boundary-wXwEgXFqE4g8IK5tK7fx-1678294339".
boundary=> \c template1
psql (15.2, server 14.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
You are now connected to database "template1" as user "v-token-to-boundary-wXwEgXFqE4g8IK5tK7fx-1678294339".
template1=> \c boundary
psql (15.2, server 14.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
You are now connected to database "boundary" as user "v-token-to-boundary-wXwEgXFqE4g8IK5tK7fx-1678294339".
boundary=>
```
worker logs:
```
2023-03-08 18:21:17	
{"id":"fnLmltIgKP","source":"https://hashicorp.com/boundary/boundary-worker-2/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_4PpHrrIzkj","msg":"connection closed","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:21:17.485885953Z"}
2023-03-08 18:21:17	
{"id":"DkeRuipa3I","source":"https://hashicorp.com/boundary/boundary-worker-1/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_fwNgjRHqxc","msg":"connection successfully authorized","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:21:17.239892133Z"}
2023-03-08 18:21:11	
{"id":"AwcmzdnSHY","source":"https://hashicorp.com/boundary/boundary-worker-2/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_ECLeR0Ofgy","msg":"connection closed","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:21:11.261489356Z"}
2023-03-08 18:21:11	
{"id":"5BQrwsyHfi","source":"https://hashicorp.com/boundary/boundary-worker-2/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_4PpHrrIzkj","msg":"connection successfully authorized","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:21:11.00636372Z"}
2023-03-08 18:21:07	
{"id":"XB9t2rnwpF","source":"https://hashicorp.com/boundary/boundary-worker-0/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_ws63P0eX3G","msg":"connection closed","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:21:07.306472333Z"}
2023-03-08 18:21:07	
{"id":"jPheN4Lmrm","source":"https://hashicorp.com/boundary/boundary-worker-2/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_ECLeR0Ofgy","msg":"connection successfully authorized","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:21:07.04724777Z"}
2023-03-08 18:20:55	
{"id":"rmwKrVMLUE","source":"https://hashicorp.com/boundary/boundary-worker-2/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_l8v6vybqr4","msg":"connection closed","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:20:55.98026783Z"}
2023-03-08 18:20:55	
{"id":"PAEA29H6oM","source":"https://hashicorp.com/boundary/boundary-worker-0/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_ws63P0eX3G","msg":"connection successfully authorized","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:20:55.727460666Z"}
2023-03-08 18:20:47	
{"id":"vypJCMLw3I","source":"https://hashicorp.com/boundary/boundary-worker-1/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_flFLQqFVrC","msg":"connection closed","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:20:47.497672498Z"}
2023-03-08 18:20:47	
{"id":"Lcv9ARDS8s","source":"https://hashicorp.com/boundary/boundary-worker-2/worker","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"worker.(Worker).handleProxy","data":{"connection_id":"sc_l8v6vybqr4","msg":"connection successfully authorized","session_id":"s_TpcIVTaLVL"}},"datacontentype":"application/cloudevents","time":"2023-03-08T17:20:47.215163255Z"}
```
