### ISSUE TITLE
Auth token time to live not adjustable

### ISSUE THREAD

**Issue by jeremy-rescale** [hashicorp/boundary#3176]
**Describe the bug**
When I set the `auth_token_time_to_live` in the `controller` stanza, it does not have any affect.

**To Reproduce**
1. Use controller stanza:
```
controller {
    name = "kubernetes-controller"
    description = "A controller for a kubernetes"
    database {
    url = "env://BOUNDARY_PG_URL"
    }
    public_cluster_addr = "env://BOUNDARY_CONTROLLER_URL"
    auth_token_time_to_live = "12h"
}
```
2. Authenticate: `boundary authenticate`
3. Read token: `boundary auth-tokens read -id self`
4. Expiration time is 7 days (default)
```
Auth Token information:
  Approximate Last Used Time:   Fri, 21 Apr 2023 14:47:50 CDT
  Auth Method ID:               amoidc_xxxxxxx
  Created Time:                 Fri, 21 Apr 2023 14:37:09 CDT
  Expiration Time:              Fri, 28 Apr 2023 14:37:09 CDT
```

**Expected behavior**
Expiration Time should be 12h more than Created Time

**Additional context**

**Comment by PPacent** [comment]
@rescale-jeremy thanks for reporting this bug. We will investigate to reproduce and fix if applicable. Stay tuned!

**Comment by jefferai** [comment]
This is working fine for me. Can you verify if you are using multiple controllers, and if so if you have put that value on all controller configs?

**Comment by rescale-jeremy** [comment]
Just using a single controller.

**Comment by PPacent** [comment]
Which version of Boundary are you running and what type of system are you running it on @rescale-jeremy?

**Comment by rescale-jeremy** [comment]
Controller is using `0.12.0` running in aws eks.  Locally ubuntu client is `0.12.0` and `0.12.2`.  Also tested with local mac client version `0.12.2`

**Comment by jefferai** [comment]
Curious about something, when you authenticate it displays token output including TTL. In your repro case above you are doing a read on the token, are you seeing different values between the two times the info is output?

**Comment by rescale-jeremy** [comment]
When I authenticate, it shows 7 days as well
```
Authentication information:
  Account ID:      acctoidc_xxxxx
  Auth Method ID:  amoidc_xxxxxx
  Expiration Time: Mon, 08 May 2023 15:00:24 CDT
  User ID:         u_xxxxxx
```

**Comment by jefferai** [comment]
Stupid question (mainly because I cannot figure out how to reproduce this so I don't have good questions :-D ): are you sure that Boundary is using _this config file_? Given that you're using env vars for some of the important bits it might not be obvious if something is wrong...is there a chance there is a difference config file that is actually being used?

**Comment by rescale-jeremy** [comment]
Not a stupid question, as  I was wondering the same thing. It's the only config file on the pod and without all of the other stuff in the config file, the pod wouldn't start up.  Is there a way to determine from boundary, which config file it's using?

**Comment by jefferai** [comment]
No -- it'd be that one, as Boundary doesn't support config file merging. So if you remove it and Boundary doesn't start up, chances are it's using that one :-)

**Comment by PPacent** [comment]
Hi @jeremy-rescale are you still running into this issue? We have not been able to reproduce internally and will close this issue out if we don't hear back. Thank you!

**Comment by jeremy-rescale** [comment]
@PPacent I am not! I have no idea what has changed. We haven't updated version of boundary or anything, but I'm glad it's resolved!
