### ISSUE TITLE
Page Not found

### ISSUE THREAD

**Issue by thatsk** [hashicorp/boundary#3359]
**Describe the bug**
When i click on link page not found Pls check

**To Reproduce**
1. https://www.boundaryproject.io/use-cases/session-recording?product_intent=boundary
2. See error
![image](https://github.com/hashicorp/boundary/assets/15324013/866de831-f2dd-4ae8-b83e-7c712287ce6b)

**Expected behavior**
it should show information about functionality

**Additional context**

**Comment by AdamBouhmad** [comment]
Hey thatsk, the correct link appears to be https://www.boundaryproject.io/use-cases/session-recording-and-audit-logs. What link did you click that directed you to https://www.boundaryproject.io/use-cases/session-recording?

**Comment by thatsk** [comment]
yes when i am navigating from https://www.boundaryproject.io/ this to

**Comment by AdamBouhmad** [comment]
Resolved -- thanks for pointing this out @thatsk!
