### ISSUE TITLE
Adding support for agent forwarding in built-in SSH

### ISSUE THREAD

**Issue by redat00** [hashicorp/boundary#3461]
**Is your feature request related to a problem? Please describe.**

In some context it's required to forward your SSH agent as you connect to server. For example if you know that you will then connect to another server after accessing the first, forwarding your SSH agent so that your SSH key follows you is mandatory. To this day this is not possible to do with the built-in SSH connect method.

**Describe the solution you'd like**

The solution I would like is a flag for the `boundary ssh connect` command that would allow me to tell it to forward my SSH agent (using the `-A` argument). 

```bash
boundary connect ssh -target-name myserver -target-scope-name "production" -forward-agent
```

**Describe alternatives you've considered**

The alternative I've considered is by not using the built-in SSH, but by just relying on the proxy of my SSH command.

**Additional context**

I'm able to do the PR as I was able on my local host to modify the code base and add the ability of forwarding my SSH agent. This issue is mostly to follow the recommendation inside of the CONTRIBUTING.md doc that recommends asking first to see if the feature is relevant, or not inside of the pipeline.

Thanks in advance for any time anyone might give me !

**Comment by AdamBouhmad** [comment]
Hey @redat00, thanks for submitting an issue! 

Within the boundary connect subcommand, there is an optional exec flag, which allows you to pipe arguments directly to the binary being invoked. The connect subcommand has this option documented: 

` -exec=<string>
      If set, after connecting to the worker, the given binary will be
      executed. This should be a binary on your path, or an absolute path. If
      all command flags are followed by " -- " (space, two hyphens, space),
      then any arguments after that will be sent directly to the binary.
      This can also be specified via the BOUNDARY_CONNECT_EXEC environment
      variable.`

In this case, to use SSH Agent Forwarding while using boundary connect, you would do:  `boundary connect ssh -target-id <target-id> -- -A` , with everything after -- being passed to the ssh binary. 

Hopefully this is helpful. Does this satisfy your use-case here?

**Comment by omkensey** [comment]
I believe you can also pass SSH flags using the double dash that way with `boundary connect ssh` as well.

**Comment by redat00** [comment]
Hello ! 

Yes in fact this is great, sorry I didn't see it at first glance in the documentation. 
This is perfect for my use case. 

Thanks a lot !
