### ISSUE TITLE
Workaround for using paramiko to connect to ssh target with credential injection

### ISSUE THREAD

**Issue by somurzakov** [hashicorp/boundary#3802]
**Describe the bug**
If anyone is using Paramiko library and cannot connect to ssh target with credential injection, because it throws some cryptic error
`ValueError: Not enough fields for public blob: []` use the workaround below:

**To Reproduce**
1. Create target of type=ssh, link Credential Library of type Vault, use ssh-signer secrets engine in Vault to issue SSH certificate for auth
2. Run `boundary connect -target-id tssh_abcdefg -listen-port 10000`
3. run python code:
```
import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('localhost', port=10000, username='ubuntu', password='default', timeout=3)
```

**Workaround**
Use auth_strategy=NoneAuth('') parameter when creating paramiko client.
```
import paramiko
from paramiko.auth_strategy import NoneAuth

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('localhost', port=10000, auth_strategy=NoneAuth(''))

stdin, stdout, stderr = client.exec_command("whoami")
print(stdout.readlines())
```
output: `ubuntu`

**Comment by PPacent** [comment]
Hi @somurzakov, this seems to be an issue on the paramiko side:  https://github.com/paramiko/paramiko/issues/1448 which I saw you already commented on with a workaround. Is this workaround sufficient? If so we will close this out

**Comment by somurzakov-rbx** [comment]
yes, this issue can be closed, I just wanted to post it so that if someone googles the problem it can be found

**Comment by PPacent** [comment]
makes sense, thank you @somurzakov
