### ISSUE TITLE
Org level Credential Store(s)

### ISSUE THREAD

**Issue by chuckyz** [hashicorp/boundary#3854]
Today, when creating credential stores we have a bit of scope creep leading to a lot of friction for creating credential stores.  We have secrets which _should_ be shared across projects, and because of the way Boundary deals with this, we have to end up creating a bunch of different tokens with the same level of access.  This feels a little bit backwards. 

Ideally, we can move most of these credential stores up to org-level shared credential stores to be shared across all the projects.

As an alternative, we are creating many duplicates of credentials and spreading them across projects.

**Comment by AdamBouhmad** [comment]
Thanks for submitting this feature request 

After some internal discussion, we've decided Org Level Credential Stores is not something we're considering in the near future.

**Pros to implementation**
There are some benefits to an implementation here. As an example, for smaller organizations, the Global, Org, and Project admin may be collapsed onto a single or set of administrators. In this case an org level Credential Store may make perfect sense from an administrative perspective. 

Additionally, Org-Level Credential Stores would be a simplified method of getting started with Credential Management in Boundary. As an Organization matures, they should shift to Project-Level Credential Stores that are more tightly scoped by their intended use. 

**Reasons for not proceeding with implementation**
- Credential Stores are designed to be tightly scoped to the scope they are in for the sake of least privilege
    - The benefit of the current model is that it’s more granular; project admins need to confirm ownership of the rights within vault to access credentials, versus access to credentials just simply being delegated by the Org Admin, intentionally or not.

- There’s a risk with having Credential Stores at the Org scope. Incorrect permissioning could lead to unintended sharing of credential libraries across child projects.
  - In a least-privileged environment where the Org admin doesn’t necessarily have access to the project scopes, you may not know who you’re sharing the credentials with as more projects are added, this could result in unintended privilege escalation

- Creating Credential Stores with identical permissions in another scope is an acknowledgement of risk associated with credential re-use 
  - As an example, we don't allow the same vault token to be re-used across credential stores for this reason 

There's certainly a balance here between Usability & Security. We're confident that tightly scoped credential stores at the project level is a great security feature for administrators, requiring them to put thought into what credentials should be used where, and preventing unintended privilege escalation. Additionally, with terraform, management of credential stores across a boundary env becomes pretty trivial. 


Thanks again for the FR.
