### ISSUE TITLE
Restricting credentials from specific credential stores while adding credentials in the targets

### ISSUE THREAD

**Issue by japneet-sahni** [hashicorp/boundary#3956]
**Describe the bug**
I have following requirements for a team admin (not the boundary admin) :

- The team admin should have access to already existing target created by boundary admin
- The team admin should have access to already existing credential store created by boundary admin
- The team admin should have access to manage credentials in the credential store which he has access to.
- The team admin should have access to add brokered credentials to targets but these credentials should be part of a credential store only which he has access to.

**To Reproduce**
1. Create a target, lets say with id=tssh_ORCiogFU7y
2. Create a static (not vault) credential store with id=csst_dPYVCZUAcK
3. Create another static (not vault) credential store with id=csst_XyvCfwVURD
4. Create couple of credentials in both stores.
5. Add following grants for the team admin

_id=*;type=target;actions=list,no-op
id=tssh_ORCiogFU7y;actions=read,update,authorize-session,set-credential-sources,add-credential-sources,remove-credential-sources
id=csst_dPYVCZUAcK;actions=read,update
id=*;type=credential;actions=list,read,create,update,delete
id=*;type=credential-store;actions=list,no-op
id=*;type=session;actions=read:self,cancel:self_

6. Login to Boundary UI (not desktop) using team admin's credentials.
7. The team admin is correctly able to see the target and credentials stores and able to manage the credentials within that credentials store (Remember he doesn't have access to the other credential store)
8. **The team admin is able to add brokered credentials from his assigned credential store but he is also able to add credentials from the credential source which he doesn't has access to.**

**Expected behavior**
The team admin should be able to add brokered credentials only from his assigned credential store and shouldn't be able to add credentials from the credential source which he doesn't has access to.

**Additional context**

**Comment by AdamBouhmad** [comment]
Hey @japneet-sahni, 

I've tried reproducing the issue here but havent had any luck. For the relevant roles, can you provide the output from: 
`boundary roles read -id <role-id>`

Thank you!

**Comment by japneet-sahni** [comment]
@AdamBouhmad : PFB details for targets, credential stores, credentials and roles.
- Created 2 targets (target-1 and target-2)
- Created 2 cred stores (cred-store-1 and cred-store-2)
- Created credentials cred-1 and cred-2 in cred-store-1 and cred-3 in cred-store-3
- Created role to give access to user1 to target-1 and cred-store-1 but able to see credentials from cred-store-2 as well (cred-3) while adding brokered credentials in target-1
`
**boundary targets list -scope-id=p_uy3AwapIbS**

Target information:
  ID:                    ttcp_m1LuW4BVyq
    Version:             1
    Type:                tcp
    Name:                target-1
    Address:             1.2.3.4
    Authorized Actions:
      no-op
      read
      update
      delete
      add-host-sources
      set-host-sources
      remove-host-sources
      add-credential-sources
      set-credential-sources
      remove-credential-sources
      authorize-session

  ID:                    ttcp_niAarjKyuG
    Version:             1
    Type:                tcp
    Name:                target-2
    Address:             1.2.3.4
    Authorized Actions:
      no-op
      read
      update
      delete
      add-host-sources
      set-host-sources
      remove-host-sources
      add-credential-sources
      set-credential-sources
      remove-credential-sources
      authorize-session

**boundary credential-stores list -scope-id=p_uy3AwapIbS**

Credential Store information:
  ID:                    csst_Yzy9fSMben
    Version:             1
    Type:                static
    Name:                cred-store-1
    Authorized Actions:
      no-op
      read
      update
      delete

  ID:                    csst_SBEkNt3duV
    Version:             1
    Type:                static
    Name:                cred-store-2
    Authorized Actions:
      no-op
      read
      update
      delete

**boundary credentials list -credential-store-id csst_Yzy9fSMben**

Credential information:
  ID:                    credup_f5h3qxRJBI
    Version:             1
    Type:                username_password
    Name:                cred-1
    Authorized Actions:
      no-op
      read
      update
      delete

  ID:                    credup_SOYPOH8cVZ
    Version:             1
    Type:                username_password
    Name:                cred-2
    Authorized Actions:
      no-op
      read
      update
      delete

**boundary credentials list -credential-store-id csst_SBEkNt3duV**

Credential information:
  ID:                    credup_cZCUKDG9JD
    Version:             2
    Type:                username_password
    Name:                cred-3
    Authorized Actions:
      no-op
      read
      update
      delete

**boundary roles read -id r_VSCHf3KqEU**

Role information:
  Created Time:        Tue, 31 Oct 2023 10:03:20 EDT
  Grant Scope ID:      p_uy3AwapIbS
  ID:                  r_VSCHf3KqEU
  Name:                target1-admin
  Updated Time:        Tue, 31 Oct 2023 10:05:01 EDT
  Version:             3

  Scope:
    ID:                p_uy3AwapIbS
    Name:              Password Vault
    Parent Scope ID:   o_1234567890
    Type:              project

  Authorized Actions:
    no-op
    read
    update
    delete
    add-principals
    set-principals
    remove-principals
    add-grants
    set-grants
    remove-grants

  Principals:
    ID:             u_p4TISJjTFu
      Type:         user
      Scope ID:     global

  Canonical Grants:
    id=*;type=credential-store;actions=list,no-op
    id=*;type=credential;actions=create,list,read,update
    id=*;type=session;actions=cancel:self,read:self
    id=*;type=target;actions=list,no-op
    id=csst_Yzy9fSMben;actions=read,update
    id=ttcp_m1LuW4BVyq;actions=add-credential-sources,authorize-session,read,remove-credential-sources,set-credential-sources,update`

**PFB snapshots of Boundary UI when logged in as user1. In the last snapshot, you'll notice cred-3 popping up when the user doesn't have access to cred-store-2.**

<img width="1067" alt="image" src="https://github.com/hashicorp/boundary/assets/10338163/d8732d68-7972-4721-bdea-a740f53bc083">
<img width="771" alt="image" src="https://github.com/hashicorp/boundary/assets/10338163/e6033745-e983-4e76-bd91-16378c80124f">
<img width="855" alt="image" src="https://github.com/hashicorp/boundary/assets/10338163/4211e037-a230-4f79-a40f-68d49d830f66">
<img width="894" alt="image" src="https://github.com/hashicorp/boundary/assets/10338163/2265d609-6470-46e8-9652-b5824eb3eff0">

**Comment by japneet-sahni** [comment]
@AdamBouhmad : Any update on this issue. Do you think if I am missing any grant for this role?

**Comment by AdamBouhmad** [comment]
Hey @japneet-sahni, we're doing some triage internally and should get back to your early next week.

**Comment by AdamBouhmad** [comment]
Thanks again for raising this issue. 

In chatting with the team, this is working as intended. Projects are permission domains. To achieve you’re goal of team-admins with CRUDL to specific credentials within a credential store, it may be best to separate the credential stores into separate projects, and assign those team-admins project-level roles as needed. 

I would keep in mind that as of Boundary 0.10, you can do cross-scope IAM associations, e.g expanding an association in a project scope to resources such as group members and principals that reside in other scopes. This seems like it would achieve your goal of relegating access to specific credential stores(and the credentials within) to particular team-admin users. Does splitting out your static credential stores per-project suit your use-case here?

**Comment by japneet-sahni** [comment]
Thanks @AdamBouhmad for this explanation. In that case, we will create separate Boundary projects in this case for every credential store with some cross-scope IAM associations. I have tried this and it solves our use-case now. We cam mark this bug as closed now.

**Comment by AdamBouhmad** [comment]
Thanks for the response back @japneet-sahni. 

As always, feel free to raise additional issues/feature requests as it makes sense.
