### ISSUE TITLE
Do Boundary Hashicorp owns Maximum Session Limitation

### ISSUE THREAD

**Issue by Jim0530** [hashicorp/boundary#4096]
As my title says, do the community version of Hashicorp has some contraints on session?

**Comment by AdamBouhmad** [comment]
Hey Jim -- session controls are the same across editions of Boundary, this[ includes setting a session_connection_limit or session_max_seconds](https://developer.hashicorp.com/boundary/docs/concepts/domain-model/targets#attributes) on a Target, and the ability to [manage sessions as an Administrator](https://developer.hashicorp.com/boundary/tutorials/oss-administration/oss-manage-sessions). The only difference is the ability to Record Sessions, which is available in HCP/Enterprise only. 

Does this answer your question?
