### ISSUE TITLE
Client connect error with client 0.15.0

### ISSUE THREAD

**Issue by umglurf** [hashicorp/boundary#4364]
**Describe the bug**

After upgrading boundary controller and worker to 0.15.0, connections fails when using boundary client 0.15.0, but using boundary client 0.14.3 connections works.

**To Reproduce**
1. Run `boundary connect  -target-id=xx -host-id=xx`
2. Run `nc 127.0.0.1 port_number`
3. See error

**Expected behavior**
Connections work with client version 0.15.0 as they do with client 0.14.3

**Additional context**

Nothing in either the controller og worker logs

**Comment by logamanig** [comment]
same issue for us as well. so, I'm now running

Controller: 0.15.0
Worker: 0.14.3
Client: 0.15.0 

to get this working around

**Comment by elimt** [comment]
Hey @umglurf ,

I've tried reproducing the issue here but haven't had any luck. Can you please provide some more information about your set up. Your controller is 0.15.0, worker is 0.15.0 & your CLI client is 0.15.0?
Also, what OS are you using?

**Comment by elimt** [comment]
@umglurf Thanks!

What is the error thrown when you attempt to connect to the authorized session `nc 127.0.0.1 port_number`?

**Comment by umglurf** [comment]
> What is the error thrown when you attempt to connect to the authorized session `nc 127.0.0.1 port_number`?

I've made a short recording showing what happens 
[Screencast from 2024-02-08 06-12-21.webm](https://github.com/hashicorp/boundary/assets/15076744/ca1008eb-9d8c-42e1-8491-4e865faf89d0)

**Comment by umglurf** [comment]
> @umglurf Thanks for the video. That helps a lot
> 
> What is the maximum number of connections configured for your target?

Hi, the session max connection limit is set to 1. I tried increasing it to 2, and then it works with 0.15.0, so could it be something has changed in 0.15 that now requires an extra connection?

**Comment by umglurf** [comment]
Hi @elimt 

I tested the released 0.15.1 now and it works again with that version. Thanks for the fix
