### ISSUE TITLE
Possibility of providing connect wrapper extensions via wasi

### ISSUE THREAD

**Issue by kesavkolla** [hashicorp/boundary#4382]
With wasm getting more traction It's super cool extend the functionality of boundary connect wrappers using wasm. If boundary can leverage https://github.com/extism/extism for loading plugins then anyone with any programming language can develop the connect wrapper and be able to use boundary connect. Currently only go programmers can do the boundary build for custom connect subcommands.

**Comment by jefferai** [comment]
wasm has always been of interest to us (we designed session activation to be able to eventually support it, prior to public release!). I think it's more likely we'd support it generally for connecting than specifically to create custom connect subcommands, and any such commands are just syntactic sugar -- they're the equivalent of running `boundary connect -exec` and passing a number of functions to the eventual call. That said if it's supported more generally for connection than any desired wrapping command could be created.

**Comment by jefferai** [comment]
I'm going to close this as this specific ask is not a near term item for us but wasm support is definitely something we're interested in!
