### ISSUE TITLE
LDAP auth method Account Attribute Maps not populating

### ISSUE THREAD

**Issue by bbarkhouse-hashicorp** [hashicorp/boundary#4422]
**Describe the bug**
When account attribute maps are set within a LDAP auth method, the From Attributes are not populating the To Attributes in the individual user accounts.

**To Reproduce**
1. Create a new LDAP auth method
2. Configure all settings and set the account attribute map based on the user attributes in your directory. In my case I mapped cn to fullName and mail to email.
3. Save and enable the auth method.
4. Open Boundary Desktop, select the scope and LDAP auth method just created
5. Log in with valid users credentials from the target LDAP user dn
6. Boundary Desktop successfully authenticates and takes me to the list of targets
7. Go back to the admin UI and you will see the new account associated with the LDAP auth method. However only the id, DN and groups attributes are populated. Full Name and Email are blank even though they were mapped in the auth method config.

**Expected behavior**
When account attribute maps are set within a LDAP auth method, I expect the attributes to populate the user account with values. For example, if cn is mapped to fullName, when the LDAP user authenticate to Boundary, the user account gets created in Boundary but the Full Name field is blank. I expected the cn value to be populated.
![Screen Shot 2024-02-16 at 13 16 21 PM](https://github.com/hashicorp/boundary/assets/84409718/87dd0660-2cdb-4e48-a30e-49f173d9f768)
![Screen Shot 2024-02-16 at 13 19 15 PM](https://github.com/hashicorp/boundary/assets/84409718/70a83c3d-565e-4848-8847-d6f8bbd5c720)

**Comment by moduli** [comment]
Thanks for raising this issue. We've implemented a fix [here](https://github.com/hashicorp/boundary/pull/4788) and it should be included in the next non-patch release of Boundary.
