### ISSUE TITLE
Mask passwords but not usernames

### ISSUE THREAD

**Issue by itsphoebe** [hashicorp/boundary#4570]
**Is your feature request related to a problem? Please describe.**
When setting `secret  = "redact"` for audit filter, it redacts both username and password audit info, making it difficult to use the audit logs to understand who the log came from. 

**Describe the solution you'd like**
Have config to allow redact of passwords and not usernames.

**Comment by jimlambrt** [comment]
I believe both password and ldap auth methods have the username (which is PII) classified as sensitive, which seems appropriate.  You can override the "masking" of sensitive data if you wish (see: https://developer.hashicorp.com/boundary/tutorials/self-managed-deployment/event-logging)
