### ISSUE TITLE
No ability to delete Storage Bucket from admin UI 

### ISSUE THREAD

**Issue by hillout** [hashicorp/boundary#4769]
It's kinda funny that there is no ability to delete unwanted Storage Bucket for session recording in 0.16 version. 
![Screenshot from 2024-05-06 10-46-59](https://github.com/hashicorp/boundary/assets/15137897/9760bb3e-002a-45d5-b2be-baf0aa38d82f)

There is only edit button and that's it.

**Comment by cameronperera** [comment]
Hi @hillout,

Thank you for reaching out about this issue. Deletion of a Storage Bucket has not been implemented in the UI but is on our backlog. In the meantime, I would recommend using `boundary storage-buckets delete -id <storage_bucket_id>` to remove any unwanted Storage Buckets and please see our [Storage Bucket docs](https://developer.hashicorp.com/boundary/docs/commands/storage-buckets/delete) for more information.

**Comment by hillout** [comment]
@cameronperera 
Thanks, just wanted to point it out :)
