### ISSUE TITLE
Boundary Init not working if extension citext already exists

### ISSUE THREAD

**Issue by tgahlx** [hashicorp/boundary#4932]
**Describe the bug**
Boundary init fails with

```
create extension "citext";: unknown: error #0: ERROR: extension "citext" already exists (SQLSTATE 42710)
```

**To Reproduce**
1. Manually create extension citext in schema 
2. Run `boundary init`
3. See error

**Expected behavior**
Boundary init accepts if extension citext already exists.

**Additional context**
Migration ignores if database already exists:
https://github.com/hashicorp/boundary/blob/main/internal/db/schema/migrations/oss/postgres/85/01_citext_extension.up.sql#L9

Problem doesn't occur for e.g. pgcrypto:
https://github.com/hashicorp/boundary/blob/main/internal/db/schema/migrations/oss/postgres/0/60_wh_domain_types.up.sql#L6

**Comment by mgaffney** [comment]
Duplicate #4859
