### ISSUE TITLE
Scp crushes session recording

### ISSUE THREAD

**Issue by hillout** [hashicorp/boundary#5004]
**Describe the bug**
There is a clear bug with session recording. Once you log in to a target via ssh and session starts recording, open a new terminal and try to copy something over ssh via `scp -P 35901 /home/john/mongodb-compass_1.43.0_amd64.deb john@127.0.0.1:/home/john/upload_test`. Stop the session in boundary. Check the recording, there will be something like this: 
![Screenshot from 2024-08-09 14-04-27](https://github.com/user-attachments/assets/37a9fcd0-b59a-41a4-9e9b-bae96fd2b3e3)

Session details: "Failed". 

**To Reproduce**
1. Run boundary controller and worker.
3. Add a ssh target. 
4. SSH to the target using Boundary Client.
5. Open an additional terminal and try to scp some file to the target.
6. Stop the session from Boundary Client. 
7. Check session recordings from Boundary Admin UI.

**Expected behavior**
I can see both channels - first is for scp, second - is for a terminal session and I can playback them.

**Additional context**
As for storage I used Minio.

**Comment by moduli** [comment]
Thanks for reporting. We were able to successfully reproduce the error and have filed a ticket internally.
