### ISSUE TITLE
Both branches of `if-then-else` are identical

### ISSUE THREAD

**Issue by chavacava** [hashicorp/boundary#5205]
https://github.com/hashicorp/boundary/blob/1f0bad4d482c66a75da7b407f56fd3437aec85a7/internal/iam/repository_principal_role_test.go#L144-L148

https://github.com/hashicorp/boundary/blob/1f0bad4d482c66a75da7b407f56fd3437aec85a7/internal/iam/repository_principal_role_test.go#L153-L157

Found with [revive](https://github.com/mgechev/revive/)

**Comment by bgajjala8** [comment]
Hi! I’ve submitted a fix to clean up the redundant code 

[https://github.com/hashicorp/boundary/pull/5211](PR)
