### ISSUE TITLE
Docs are missing the possible permissions actions

### ISSUE THREAD

**Issue by shellwhale** [hashicorp/boundary#5233]
Where are the docs for the possible actions permissions?
https://github.com/hashicorp/boundary/blob/514bcc19f605a03c004df0d78cd790e54a2f8c73/internal/types/action/action.go#L162

**Comment by Dan-Heath** [comment]
Hello @shellwhale, thanks for your question. We have documentation on permissions here:

- [Identity and access management (IAM)](https://developer.hashicorp.com/boundary/docs/concepts/iam)
- [Permissions in Boundary](https://developer.hashicorp.com/boundary/docs/configuration/identity-access-management)
- [Assignable permissions](https://developer.hashicorp.com/boundary/docs/configuration/identity-access-management/assignable-permissions)
- [Permission grant formats](https://developer.hashicorp.com/boundary/docs/configuration/identity-access-management/permission-grant-formats)
- [Manage roles](https://developer.hashicorp.com/boundary/docs/common-workflows/manage-roles)
- [Resource tables](https://developer.hashicorp.com/boundary/docs/configuration/identity-access-management/resource-table)

Please let me know whether those pages answer your question, or if there is something else you are looking for. Thank you!

**Comment by shellwhale** [comment]
Hello @Dan-Heath, thanks for the answer.
From your links the only page that mentions a list of possible action is this one : https://developer.hashicorp.com/boundary/docs/configuration/identity-access-management/assignable-permissions#actions

But that is really lacking

**Comment by Dan-Heath** [comment]
Thanks for your reply @shellwhale. Did you see the [Resource tables](https://developer.hashicorp.com/boundary/docs/configuration/identity-access-management/resource-table) topic? I think it might have the information you are looking for. It has a list of available actions per resource. The available actions are listed in the right-hand column of the tables for each resource type with examples.

Please let me know if that helps. We are planning a refresh of this part of the docs for early next year. I know this information could be better organized - it is spread out over multiple topics, and it makes it difficult to find. If you have any suggestions for improvement, please let me know and I can add them to our planned work.

**Comment by shellwhale** [comment]
Thank you @Dan-Heath, it did not seems obvious in the resource table indeed, I overlooked it sorry for that.

Yes it is better!
