### ISSUE TITLE
Usage output for plural objects (host-catalogs and host-sets) not correct, missing dash

### ISSUE THREAD

**Issue by eyenx** [hashicorp/boundary#686]
**Describe the bug**
The help function isn't showing the correct syntax of the command itself

**To Reproduce**
1. Run `boundary host-catalogs list -help` or `boundary host-sets list -help`
2. Returns: 
```
Usage: boundary host catalogs list [options] [args]

  List host catalogs within an enclosing scope or resource. Example:

    $ boundary host catalogs list
```

which is wrong (missing dash between host and catalogs in the usage example)

**Expected behavior**
Should output:

```
Usage: boundary host-catalogs list [options] [args]

  List host catalogs within an enclosing scope or resource. Example:

    $ boundary host-catalogs list
```

**Additional context**
Might be due to this plural settings:

https://github.com/hashicorp/boundary/blob/main/internal/cmd/commands/hostcatalogs/hostcatalog.go#L170

**Comment by jefferai** [comment]
I've created #689 to address this, thanks for the report!
