### ISSUE TITLE
Azure AAD OIDC Authentication

### ISSUE THREAD

**Issue by jalleyne** [hashicorp/boundary#690]
**Is your feature request related to a problem? Please describe.**
This is pretty self explanatory but having access to this now would be valuable. I am coincidentally in the middle of setting up several terraform plans to get a VPN gateway running in azure so that k8 cluster can be configured for private networking only.

**Describe the solution you'd like**
Connect to azure ad as a gallery application and allow users in specific ad groups to login then have scopes assigned to these users mapped to their groups.

**Describe alternatives you've considered**
Existing username and password auth in Boundary, but outside of that Azure VPN supports this on windows only unfortunately.

**Comment by jalleyne** [comment]
I understand the from the docs that the oidc integration is in the roadmap. Does that mean it's actively being developed or is it open for public contributions?

This seems like a really interesting project, could try putting an MVP together if it's not in the near roadmap from the core team.

**Comment by jefferai** [comment]
It's in the very near roadmap! We'll be using the same underlying oidc code as Vault so if that is working for you for oidc auth then boundary will too!

**Comment by malnick** [comment]
Thanks again @jalleyne for the question, we're going to close this out since it's on our near term road map. Cheers!
