### ISSUE TITLE
SSH connection to target with port forwarding

### ISSUE THREAD

**Issue by ilyamochalov** [hashicorp/boundary#691]
**Is your feature request related to a problem? Please describe.**
I need to be able to port forward from remote target (server with a database) to my local for accessing DB's web ui

**Describe the solution you'd like**
I would like `boundary connect ssh` to accept `ssh` cli flags like `-L` and `-R` to establish port forwarding 

**Describe alternatives you've considered**
No

**Explain any additional use-cases**
No

**Additional context**
No

**Comment by malnick** [comment]
Thanks for raising this @ilyamochalov. You can pass flags to any `connect <cmd>` or `connect -exec <cmd>` using `--`. 

For example, these two commands are the same:

```
boundary connect ssh -username foo -target ttcp_1234567890
```

or, using the `--` method: 

```
boundary connect -exec ssh -target-id ttcp_1234567890 -- malnick@{{boundary.ip}} -p {{boundary.port}}
```

In the first example, we used the built-in `ssh` sub command in the latter, we used `-exec ssh` and passed the username in through `--` to the forked ssh process. `boundary.ip` and `boundary.port` are template variables you can use for any forked command via `-exec`. Let me know if this helps!

**Comment by ilyamochalov** [comment]
@malnick thank you for the answer Jeff. Right now we are using ssh port forwarding via bastion server to access the DB's web ui:
```sh
$ ssh -L 8091:localhost:8091 ilya@server
``` 
According to your reply I should be using:
```sh
boundary connect -exec ssh -target-id ttcp_1234567890 -- ilya@server -p 8091
```
Does that crate `remote to local` port forwarding just like ssh `-L`?

**Comment by jefferai** [comment]
@ilyamochalov What @malnick was getting at is that everything after `--` is passed to the executed command, in this case `ssh`. Try this:

`boundary connect ssh -target-id ttcp_1234567890 -- -L 1890:127.0.0.1:22`

**Comment by jefferai** [comment]
@ilyamochalov I'm going to close this for now as I've tested the capability above and it should solve your issue. If we are able to implement this for various styles of client we can look into making it a built-in flag into the `ssh` subcommand.

**Comment by m-tanner-dev0** [comment]
@jefferai does this work with ssh options `-f -N`? I am having trouble getting the ssh port forwarding to occur in the background.

**Comment by jefferai** [comment]
I've never tried it, although I don't see why it wouldn't. Do you happen to have a connection limit set for the target? If so maybe the mechanism for forwarding with that style results in extra connections being made.

**Comment by m-tanner-dev0** [comment]
All I can say is that I know it doesn't work, but I can't figure out why. I have no connection limit set on the target (it's `-1`) :)

**Comment by m-tanner-dev0** [comment]
I finally got it to work.

`ssh -o ProxyCommand='sh -c "boundary connect -target-id %n -exec nc -- {{boundary.ip}} {{boundary.port}}"' ttcp_W0KVpEaHue -L 8082:127.0.0.1:22 -fNT`
