### ISSUE TITLE
Non descript error message on failed account creation

### ISSUE THREAD

**Issue by chuysmans** [hashicorp/boundary#709]
**Describe the bug**
When creating an account via the UI, its not apparent that the username must be all lowercase. The bug is the fact that the returned error via the UI doesn't describe this at all: 

```Error
The adapter operation failed due to a server error
```

**To Reproduce**
1. Connect to Boundary via the UI
1. Auth Method -> userpass -> Create Account
1. Capitalise the username field and observe the error

**Expected behavior**
If you run the same command via the CLI the returned error is much more descriptive. 

```
Oct 16 03:15:40 ip-10-0-101-209 boundary[1295]: 2020-10-16T03:15:40.383Z [ERROR] controller: internal error returned: error id=WfbRQxeQdl error="unable to create user: create: password account: invalid login name; must be all-lowercase alphanumeric: invalid parameter"
```

This same error message should be surfaced in the UI. 

**Additional context**

**Comment by jefferai** [comment]
We're working on revamping a lot of the errors for the next release, which should help here.

**Comment by talanknight** [comment]
Hi,  I just wanted to follow up since it's been 2 weeks since the last comment.  We are actively working on this issue and we hope to have a resolution soon.  Thank you for submitting this issue!

**Comment by PPacent** [comment]
Closing this issue out.
