### ISSUE TITLE
UI - Hosts added inside a host set is not actually added into to the host set.

### ISSUE THREAD

**Issue by pentiumoverdrive** [hashicorp/boundary#710]
**Describe the bug**
When adding a host from the host set, the host is created but there is no relation to host set created in the database.
The host set will always be empty if its created from the UI.

**To Reproduce**
In the UI (web interface on :9200):
    1 - Go to host catalog
    2 - Create a new host catalog (or use existing)
    3 - Create a new host set 
    4 - Go to the host sets own host tab
    5 - It’s empty. Create a host, which it says is successfully added.
    6 - Now go back to your host set, go to host tabs again…and its empty.
    7 - Go up to your host catalog again, press hosts and you can see your host there.

**The database table for members is empty:**
 select * from static_host_set_member;

**The host table contains the newly created host:**
 select * from static_host where name = ‘created_inside_newcat’;
`hst_k4MVhZujH5 | hcst_amh9fDqevR | created_inside_newcat | | 8.8.8.8 | 2020-10-15 21:24:49.939941+00 | 2020-10-15 21:24:49.939941+00 | 1`

**Expected behavior**
Ability to to manage hosts and host sets from the UI without using CLI in between.

So the admin console example on https://www.boundaryproject.io/docs/common-workflows/manage-targets#define-a-host-set  doesn't really work when adding hosts to a host set.

**Comment by jefferai** [comment]
@gsusmi Added you for tracking purposes, although I think this was resolved on Discourse?

**Comment by jefferai** [comment]
@pentiumoverdrive Can you let us know if the suggestion from Discuss worked for you?

**Comment by gsusmi** [comment]
Host association workflow ([see Admin Console tab in doc](https://www.boundaryproject.io/docs/common-workflows/manage-targets#define-a-host-set)) in UI provides a way to add hosts to host sets without running cli commands. I do believe this is resolved.

**Comment by pentiumoverdrive** [comment]
> Host association workflow ([see Admin Console tab in doc](https://www.boundaryproject.io/docs/common-workflows/manage-targets#define-a-host-set)) in UI provides a way to add hosts to host sets without running cli commands. I do believe this is resolved.

Hmm,Ok, I can create a relation now using the "manage" drop down, but one could maybe expect that when you add a host inside the host set, it should create this relation automatically?

**Comment by gsusmi** [comment]
@pentiumoverdrive , thank you for the feedback and suggestion! Will take this back to our UX designer.

**Comment by rgevaert** [comment]
I struggled with this part too. In fact when you click the add hosts link in the attached screenshot it does not add it to the hostgroup.
![image](https://user-images.githubusercontent.com/66934/96766243-10780a00-13db-11eb-9da4-444a2578e9b5.png)

Going through the manage drop down works, but I never saw it on the first few tries. If you haven't added any hosts yet,there are none to manage...

**Comment by gsusmi** [comment]
@rgevaert , Thank you for the feedback!
@pentiumoverdrive , @rgevaert: I'm working with our designer to review these workflows. Will get report back as soon as I have something. Thank you for your patience!

**Comment by jefferai** [comment]
This is resolved by https://github.com/hashicorp/boundary-ui/pull/350 which will be in 0.1.1 coming out very shortly!
