### ISSUE TITLE
minikube and "could not connect to docker: dial tcp [::1]:32770: connectex:"

### ISSUE THREAD

**Issue by darkedges** [hashicorp/boundary#720]
When using minikube as the docker container 
```
minikube start
@FOR /f "tokens=*" %i IN ('minikube -p minikube docker-env') DO @%i
boundary dev
```
it returns
```
Error creating dev database container: unable to start dev database with dialect postgres: could not connect to docker: dial tcp [::1]:32770: connectex: No connection could be made because the target machine actively refused it.
```
It looks like it is trying to connect to localhost instead of using the `DOCKER_HOST` details.

The container is running and mapped 
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                NAMES
3675ac38c494        postgres:12            "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        0.0.0.0:32770->5432/tcp   reverent_mcclintock
```

I assume this would be the case for any remotely hosted docker services.

https://github.com/hashicorp/boundary/blob/eaa2de60a9ce919a6e6858329a019ce5b5bd5613/internal/docker/supported.go#L31
```
url = "postgres://postgres:password@localhost:%s?sslmode=disable"
```
if I am reading this right it is hard coded to localhost, whilst the port is a placeholder to get the Docker Port mapped to 5432.

Would it be a good idea to map this to the variable `-host-address` that way you can specify it as part of startup? 
```
boundary dev -host-address=192.168.99.100
```
Or is there a more generic way to get the Docker IP Address from the container?

Another way to get it would be, so that you don't need to introspect the container
```
boundary dev -host-address="$(minikube ip)"
```

**Comment by malnick** [comment]
Thanks for the issue @darkedges - can you clarify the setup here, are you running Boundary in a container? 

If you are, there are a couple of caveats to be aware of:

- Dev mode won’t run unless you setup docker-in-docker because we manage a postgres container for you.
- Saving credentials will not work since most images doesn’t have dbux-x11/keyring installed.

We're working on a road map for containerized Boundary that includes K8s, most on that soon!

**Comment by darkedges** [comment]
No I am using a Remote Docker instance provided by minikube.

Boundary is expecting everything to be running on the localhost, but minikube starts an VirtualBox Machine, which runs docker as part of the OS. You connect to it remotely by using `DOCKER_HOST` i.e `DOCKER_HOST=tcp://192.168.99.100:2375` Therefore every runs on that docker host.

Does that make sense?

**Comment by malnick** [comment]
Gotcha, thanks for clarifying @darkedges. Can you clarify the end-goal for running the postgres DB for boundary in dev mode inside the minikube VM? Is this to circumvent having to install docker locally?

**Comment by malnick** [comment]
@darkedges could you try running with the `-database-url` flag?

```bash
boundary dev -database-url=postgres://postgres:password@${DOCKER_HOST}:%s?sslmode=disable
```

Let me know if this is a good workaround, I think this is what you want here.

**Comment by malnick** [comment]
@darkedges I added https://github.com/hashicorp/boundary/pull/732 to try and fix this. That allows setting the PG host to the bound IP for the container. I tested this out with:

- `minikube start`
- eval `minikube docker-env`
- `boundary dev`

Full disclaimer: I'm not an expert with minikube. It looks like it's starting up on localhost anyways, so I'm not sure how functional of of a test that was. If you get a chance to build from that PR and take it for a drive that would be great. Thanks!

**Comment by darkedges** [comment]
> @darkedges could you try running with the `-database-url` flag?
> 
> ```shell
> boundary dev -database-url=postgres://postgres:password@${DOCKER_HOST}:5432?sslmode=disable
> ```
> 
> Let me know if this is a suitable workaround, you'll need to manage the PG container on minikube out of band from the dev Boundary process.

This does not start the Postgres container if I am reading the code correctly. This assumes you already have Postgres running somewhere. So yes we could start a Postgres container, but we would also have to manage the schema etc.
