### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by sugdyzhekov** [hashicorp/boundary#721]
**Is your feature request related to a problem? Please describe.**
I want to use software that does not support the `boundary` integration. To be more specific, I want to manage databases on MySQL server in a private network. I want to do it with the help of [DataGrip](https://www.jetbrains.com/datagrip/).

**Describe the solution you'd like**
Let's allow binding to tcp port on localhost?
`boundary connect bind2localhost -local-port 3306 -target-id XXX`
and then I can use `mysql -h127.0.0.1` or DataGrip to manage my databases.

**Describe alternatives you've considered**
SSH port forwarding.

**Explain any additional use-cases**
It's a generic solution that does not depend on a specific protocol, I can establish a connection to any target that supports tcp.

**Additional context**
Nope)

**Comment by malnick** [comment]
Hi @sugdyzhekov, thanks for opening this issue! 

Take a look at the help menu for connect:
```
$ boundary connect -h
<truncated>
 -listen-addr=<string>
      If set, the CLI will attempt to bind its listening address to
      the given value, which must be an IP address. If it cannot, the
      command will error. If not set, defaults to the most common IPv4
      loopback address (127.0.0.1). This can also be specified via the
      BOUNDARY_CONNECT_LISTEN_ADDR environment variable.

  -listen-port=<int>
      If set, the CLI will attempt to bind its listening port to the given
      value. If it cannot, the command will error. This can also be specified
      via the BOUNDARY_CONNECT_LISTEN_PORT environment variable.
<truncated>..
```

You can use these flags to start a proxy session on a known bind addr and port and then you can configure datagrip to point at that instead. Let me know if this is what you were looking for and thanks for trying out Boundary!

**Comment by sugdyzhekov** [comment]
Yeah!! It works) Thanks

**Comment by kesavkolla** [comment]
@sugdyzhekov How did you solve this? Can you give me the example of the boundary connect you used? I have same requirement I want to expose my redis server, mysql server etc...?

How did you create target? What is the port number you gave inside target?

How on the client side you used it open the connection?
