### ISSUE TITLE
[Feature Request] Command whitelist/blacklist policy.

### ISSUE THREAD

**Issue by jboero** [hashicorp/boundary#739]
**Is your feature request related to a problem? Please describe.**
We're looking for some kind of whitelist option to create a policy on allowed/disallowed commands on an SSH or terminal session.  Similar to sudoers file granularity.

**Describe the solution you'd like**
A policy engine similar to Consul/Vault HCL policies that can be combined to give hierarchical access to run certain commands.  It might be nice to add functionality similar to Vault's Control Groups to allow quorum override.  Also it would be nice to allow but enable alerts on certain commands or watch filters.  Regex options would be amazing.

**Describe alternatives you've considered**
- sudoers file
- SELinux/AppArmor or other MAC enforcement

**Additional context**
This came up in a partner conversation and I'm not sure if it's on roadmap already.

**Comment by PPacent** [comment]
Thank you for trying out Boundary @jboero and raising this feature request!

This is actually a few different separate requests:
1. Command filtering
2. Policy engine integration (Sentinal and/or OPA)
3. Multi-party multi-authorization
4. Alerting

We're very aware of the interest in all of these capabilities, and we're interested in them too! It's still early days in Boundary and we can't at this point say when or in what form any of those features will show up, but we will certainly add any detail we can provide to [our public roadmap](https://www.boundaryproject.io/docs/roadmap) when possible.

For now we're going to close this ticket...it's too broad to take action on and our near-term roadmap is full, but rest assured that these use-cases are very much in our mind.
