### ISSUE TITLE
Boundary systemd file

### ISSUE THREAD

**Issue by rcomanne** [hashicorp/boundary#745]
**Describe the bug**
When taking the systemd unit file as is, it exits for me with status 213/SECUREBITS.  
Adding the SecureBits section to the service fixes this issue.
`SecureBits=keep-caps`

**To Reproduce**
1. Use the systemd unit file as is;
```
[Unit]
Description=boundary controller

[Service]
ExecStart=/usr/local/bin/boundary server -config /etc/boundary/boundary-controller.hcl
User=boundary
Group=boundary
LimitMEMLOCK=infinity
Capabilities=CAP_IPC_LOCK+ep
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK

[Install]
WantedBy=multi-user.target
```
2. Reload and run the service
3. Check status of the service or look at the log with `journalctl -u boundary-controller`

**Expected behavior**
Service starts up correctly

**Additional context**
Running on Ubuntu 16.04

**Comment by malnick** [comment]
Thanks @rcomanne - did you by chance try this out by replacing the `Capabilities` line with `AmbientCapabilities=CAP_IPC_LOCK`? I think that error is due to the version of Ubuntu not supporting this systemd value.

**Comment by rcomanne** [comment]
@malnick replacing did work, systemd file now looks like this and is starting up correctly;
```
[Unit]
Description=boundary controller

[Service]
ExecStart=/usr/local/bin/boundary server -config /etc/boundary/boundary-controller.hcl
User=boundary
Group=boundary
LimitMEMLOCK=infinity
AmbientCapabilities=CAP_IPC_LOCK
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
#SecureBits=keep-caps

[Install]
WantedBy=multi-user.target
```

**Comment by malnick** [comment]
Super, will close this out. Thanks!

**Comment by chrisfowles** [comment]
For anyone stumbling across this from google, this is also the solution for running on Amazon Linux
