### ISSUE TITLE
Boundary dev - connection closed by remote host when trying to ssh connect

### ISSUE THREAD

**Issue by edwint88** [hashicorp/boundary#748]
**Describe the bug**
I was following the tutorial from [boundary getting started](https://learn.hashicorp.com/tutorials/boundary/getting-started-connect?in=boundary/getting-started) and all worked just fine until when I had to do the following:
`boundary connect ssh -target-id ttcp_1234567890`
I get back:
`kex_exchange_identification: Connection closed by remote host`

and from the boundary:

`
2020-10-25T16:21:15.501+0100 [INFO]  controller.worker-handler: session activated: session_id=s_nIpfzJ89ao target_id=ttcp_1234567890 user_id=u_1234567890 host_set_id=hsst_1234567890 host_id=hst_1234567890
2020-10-25T16:21:15.513+0100 [INFO]  controller.worker-handler: authorized connection: session_id=s_nIpfzJ89ao connection_id=sc_5XgYcfCbUx connections_left=0
2020-10-25T16:21:15.514+0100 [ERROR] worker: error dialing endpoint: error="dial tcp [::1]:22: connect: connection refused" endpoint=tcp://localhost:22
2020-10-25T16:21:15.541+0100 [INFO]  controller.worker-handler: connection closed: connection_id=sc_5XgYcfCbUx
`

**To Reproduce**
Just follow the guide

**Expected behavior**
From the guide: _When prompted, enter the password to proceed._

**Comment by malnick** [comment]
Thanks for trying out Boundary @edwint88.

It looks like port :22 isn't available on localhost. Can you confirm SSHD is live?

**Comment by edwint88** [comment]
Starting Nmap 7.80 ( https://nmap.org ) at 2020-10-25 18:26 CET
Initiating Connect Scan at 18:26
Scanning localhost (127.0.0.1) [1 port]
Completed Connect Scan at 18:26, 0.00s elapsed (1 total ports)
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00018s latency).

PORT   STATE  SERVICE
22/tcp closed ssh

Read data files from: /usr/local/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 0.04 seconds

PS: I'm on MacOS

**Comment by malnick** [comment]
Have you enabled remote access in the sharing system preferences?

**Comment by edwint88** [comment]
this seems to work (btw is there a docker container or something like that to run boundary? ), but now when it requires my password and I type the password nothing happens. 
I am still doing the demo so the password is password:
`boundary authenticate password -auth-method-id=ampw_1234567890 -login-name=admin -password=password
` this worked, but then this `boundary connect ssh -target-id ttcp_1234567890` doesn't.

**Comment by jefferai** [comment]
Can you verify that you're able to connect to SSH _not_ through Boundary? Given that the SSH service was disabled, perhaps there is some initial setup needed and trying to go initially through Boundary is simply complicating matters.

**Comment by edwint88** [comment]
as I said, the ssh is open now (I did https://osxdaily.com/2016/08/16/enable-ssh-mac-command-line/). Now it work to connect with boundary, yesterday after entering the password either pop up to re-enter the password or it was just idle. Now seems to work and prompts me with the user@host for the second password.
