### ISSUE TITLE
I would like to offer my services to help with the documentation of your project

### ISSUE THREAD

**Issue by aardvarq** [hashicorp/boundary#751]
**Is your feature request related to a problem? Please describe.**
The documentation flows poorly. It is difficult to consume and does not address many of the items one might need to instantiate a running service. 

**Describe the solution you'd like**
I'd like someone to run through the documentation as though you have no idea how to use the product and see how you make out. I'm perplexed that there is so much work in tidying up a dev release and so little thought put into those of us who need something more robust. I've been doing this long enough that documentation is usually there to fill in some blanks as needed. In this instance, I'm at a total loss. I simply don't understand how to set up a basic service and the documentation does _not_ support my requirements.

**Describe alternatives you've considered**
I've tried "winging it"

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by aardvarq** [comment]
https://learn.hashicorp.com/tutorials/boundary/getting-started-config?in=boundary/getting-started makes zero mention of KMS, which is required and has specific configuration requirements that are not addressed.

Nowhere in the documentation can I find such basics as definitions for "controller" or "worker". 

I understand this is still beta, but how do beta testers sample the tech without appropriately detailed guidance? Am I trying to build an infrastructure that hasn't been scoped yet? The dev startup is heavily documented and seems to have been the focus of the initial release. Perhaps I'm getting ahead of things and am happy to be told thus.

**Comment by jefferai** [comment]
Hi @aardvarq ,

That page you linked to states that it assumes that Boundary is running in dev mode. In dev mode KMSes are created for you. A large part of the reason that tutorial specifies running Boundary in dev mode is specifically so it can focus on walking through functionality rather than configuration for specific environments.

**Comment by malnick** [comment]
Closing due to lack of response.
