### ISSUE TITLE
Unable to use _ or any - in user account

### ISSUE THREAD

**Issue by jsp-hashicorp** [hashicorp/boundary#759]
**Is your feature request related to a problem? Please describe.**
Unable to use _ or - in user account

**Describe the solution you'd like**
some customer user _ or - in their linux account, but in boundary it's not available to use - or _ in account settings.

**Describe alternatives you've considered**
Account setting need to accept '_' and '-'.

**Comment by jefferai** [comment]
@jsp-hashicorp What/where? Name? Description? Is this related to the user, or is it related to a password auth account, or both? an you define "account settings" better?

**Comment by jsp-hashicorp** [comment]
Hi @jefferai 
User Name, Account name and password have same issue. I can't assign any of those character any one of those three items.

**Comment by jefferai** [comment]
If it's not allowed for password that's a big. We don't allow underscores as that's reserved for IDs. But we could probably relax it to allow hyphens.

**Comment by jsp-hashicorp** [comment]
@jefferai Thanks for the quick reply. Hyphen will be enough, i think.

**Comment by jefferai** [comment]
Along with this we've had reports that passwords don't allow periods/hyphens/underscores. @mgaffney checked and said they should but when we're working on this we should probably validate that too.
