### ISSUE TITLE
Boundary CLI UX

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/boundary#766]
**Is your feature request related to a problem? Please describe.**

This is about the UX for the CLI, which breaks patterns/standards of *nix of 40+ years for CLI with long form `--option` and short form `-o`.  Thought the commands seem to work with both, just looks bizarre in documentation without the `--`.  It would be nice to have short form for things like `--password` with `-p`, and `--login-name` as `-l`.

**Describe the solution you'd like**

This is with the UX of CLI tool, so this can apply to all branches in the command.

**Describe alternatives you've considered**

Alternative is in the description, emphasize `--option` and where there's a short form, `-o`.  Have actual short forms for common repetitive options like `-p` for `password` and `-l` for `login-name`.

**Explain any additional use-cases**

The use case is all use cases that use command line options for any subcommand, and corresponding documentation.

**Additional context**

Description should be sufficient.

**Comment by jefferai** [comment]
HI there,

Apologies that the UX isn't to your liking, but at the moment there are no current plans to have short-form values. As the flags that are valid in large part vary from command to command, having meaningful short form values that are consistent would be difficult. In their current form, the flags are unambiguous and consistent, and they also match the parameters on the API, making it easy to transition between various clients (e.g. Terraform, CLI, curl).

If you're having issues with the amount of typing, we recommend installing the autocompletion support via `boundary config autocomplete install`.
