### ISSUE TITLE
Package management download steps broken for Ubuntu 20.10 users

### ISSUE THREAD

**Issue by drewdavies** [hashicorp/boundary#776]
**Describe the bug**

Ubuntu 20.10 (Groovy Gorilla) users will experience the following two issues when following the instructions within the [getting started guide](https://learn.hashicorp.com/tutorials/boundary/getting-started-install), as well as the [downloads page](https://www.boundaryproject.io/downloads):

* A deprecation warning for the `apt-key` command:
```Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).```
    * According to the man page: `apt-key(8) will last be available in Debian 11 and Ubuntu 22.04.`

* An inability to access the apt repo:
```The repository 'https://apt.releases.hashicorp.com groovy Release' does not have a Release file.```
    * The `groovy` distribution path (https://apt.releases.hashicorp.com/dists/groovy/Release) does not appear to be added to the Hashicorp public apt repo.

**To Reproduce**

On an Ubuntu 20.10 host:
1. `curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -`
2. `sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"`
3. `sudo apt-get update && sudo apt-get install boundary`

**Expected behavior**

* Adding the Hashicorp GPG key should not result in a deprecation warning, based on the provided instructions.
* Adding the Hashicorp public apt repo and downloading Boundary should complete successfully, based on the provided instructions.

**Additional context**

Using the `focal` distribution (Ubuntu 20.04) appears to complete successfully as a temporary workaround:
```
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
```

**Comment by malnick** [comment]
Thanks @drewdavies - @kylemac is going to get groovy added soon. Stay tuned.

**Comment by kpenfound** [comment]
Ubuntu Groovy has been added!

**Comment by drewdavies** [comment]
Tested the `groovy` distribution apt path and confirmed that it is working as expected, thanks for the quick turnaround!

With regards to the use of `apt-key`, there are still ~23 months remaining before it will be deprecated. While I figured it was worth bringing to the team's attention, the priority is significantly lower, so you're welcome to close this issue and track that initiative separately.

**Comment by jefferai** [comment]
@yhyakuna See the note about the getting started guide and apt-key -- can you make some kind of follow-up for the education team (I assume this is true across our various product docs) and then close this out after?

**Comment by PPacent** [comment]
@kpenfound, @yhyakuna are we ok to close this issue?

**Comment by yhyakuna** [comment]
> @kpenfound, @yhyakuna are we ok to close this issue?

I created an [Asana task](https://app.asana.com/0/563192436488770/1199159134197397/f) to track this on my end.
