### ISSUE TITLE
Documented boundary proxy command doesn't exist

### ISSUE THREAD

**Issue by jorhett** [hashicorp/boundary#800]
**Describe the bug**

Boundary proxy command documented at https://www.boundaryproject.io/docs/common-workflows/manage-sessions#advanced-session-establishment doesn't exist

**To Reproduce**

```
boundary proxy -authz foo
```

Gives error:
```
Usage: boundary <command> [args]

...
```

The command appears to actually be `boundary connect` without either a subcommand or `-exec`:

```
boundary connect  -target-scope-id=p_Foo -target-name=foo

Proxy listening information:
  Address:             127.0.0.1
  Connection Limit:    1
...
```

**Expected behavior**

Not having a subcommand is inconsistent with the help text and general command usage.

If would be more consistent to make `proxy` a subcommand.

`boundary connect proxy -target-id ttcp_foo`

**Additional context**

none

**Comment by jefferai** [comment]
The correct command is what's in the text just above that -- `boundary connect -authz-token ...` -- but it looks like the CLI example didn't get updated when the help text did.
