### ISSUE TITLE
Usability - Enable and disable dark mode

### ISSUE THREAD

**Issue by brettwilcox** [hashicorp/boundary#802]
**Is your feature request related to a problem? Please describe.**
Hello Boundary team!! 👋
I installed Boundary and started the tutorials. The first thing that jumped out at me is that there may be usability issue. It appears that the UI changes based on OS (MacOS, Safari, Dark Mode). I can see this being a usability issue for someone with eyesight issues.

**Describe the solution you'd like**
I would like to see an option to have dark mode disabled by default and have a setting in the profile to enable.

**Describe alternatives you've considered**
A way to disable dark mode.

**Additional context**
https://www.w3.org/WAI/fundamentals/accessibility-usability-inclusion/

Thank you for making this amazing project!

**Comment by randallmorey** [comment]
Thank you for your interest in Boundary!  This is really great feedback.  We did invest time into this feature, as it is handy to be able to toggle among color modes.  In the latest version of Boundary, you will find this toggle in the user dropdown in the upper righthand corner of the app.  See image.

<img width="332" alt="Screenshot 2020-11-24 at 08 59 03" src="https://user-images.githubusercontent.com/8390120/100105704-a9180480-2e35-11eb-9abc-743acafa9b8e.png">

Thanks again!  Please don't hesitate to leave additional feedback.
