### ISSUE TITLE
Postgres database password with symbols which are not a-z, A-Z, 0-9 leads to an error and cannot be set via hcl config file

### ISSUE THREAD

**Issue by skolenkin** [hashicorp/boundary#820]
Postgres database password cannot contain any symbols other than symbols and numbers. I wasn’t able to escape special symbols. But in Postgres, I can set password with special symbols. Most systems’ passwords must consist of a lengthy set of characters often including numbers, special characters, and a combination of upper and lower cases.
Example: This password ```postgres#Boundary2020``` incorrect
Error querying database for init status:
```
parse "postgresql://postgres:postgres": invalid port ":postgres" after host
Error parsing config file: At 10:3: key 'postgres' expected start of object ('{') or assignment ('=')

url = postgresql://postgres:postgres\#Boundary2020@127.0.0.1:5432/postgres?sslmode=disable"
boundary database init -config /etc/boundary/boundary.hcl
Error parsing config file: At 9:43: illegal char escape
```

```
boundary version
Version information:
  Git Revision:        d8020842ae8b6c742b94538baada313d7eb52809
  Version Number:      0.1.2
```

Expected result: any password, set by the user, applied
Current result: password is limited to a-z, A-Z, 0-9, and become not secure

References: 
1. https://cwe.mitre.org/data/definitions/521.html
2. https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/04-Authentication_Testing/07-Testing_for_Weak_Password_Policy

**Comment by malnick** [comment]
Thanks for raising this @skolenkin - can you copy/paste the URL string for the database (with redacted sensitive values) here?

It looks like the URL is malformed for the port attribute, `parse "postgresql://postgres:postgres": invalid port ":postgres" after host`

**Comment by malnick** [comment]
@skolenkin You need to use % escapes for your password since this is a URL as defined in https://www.w3schools.com/tags/ref_urlencode.ASP

**Comment by skolenkin** [comment]
I have checked and it works. 
Replaced postgres#Boundary2020 to postgres%23Boundary2020
Could you please add this information to boundary documentation?
