### ISSUE TITLE
According to the previous issue we can run boundary server and connect to WEB UI but we have black screen only.

### ISSUE THREAD

**Issue by skolenkin** [hashicorp/boundary#824]
If we use other user names than Postgres, the system user gets the following issue:
https://github.com/hashicorp/boundary/blob/main/docker/config.hcl#L9 and unsuccessfully initialized database you will see  UI with only a black screen. 

References: 
https://en.wikipedia.org/wiki/Information_security (Availability part)

**Comment by malnick** [comment]
@randallmorey @PPacent - Thoughts on having a UI screen to give a friendly "Database not initialized" screen when this is the case?

**Comment by randallmorey** [comment]
Hello there!  This is a known issue #805.  Our backend engineers are working on a fix!  Feel free to follow the original ticket to be notified of progress on this front.  Thanks for the feedback!
