### ISSUE TITLE
 Insufficient Session Expiration

### ISSUE THREAD

**Issue by skolenkin** [hashicorp/boundary#829]
I have found that boundary generates token with expiration of 7 days. Also, I wasn’t able to find how to change the expiration period parameter.

```
date
Tue Dec 15 13:48:27 EET 2020
```

```
boundary authenticate password -auth-method-id=ampw_X -login-name=admin --password=PASSWORD -addr=http://IP:9200

Authentication information:
  Account ID:      apw_X
  Auth Method ID:  ampw_X
  Expiration Time: Tue, 22 Dec 2020 13:46:03 EET
  Token:           TOKEN
  User ID:         u_X
```

```
boundary version
Version information:
  Git Revision:        d8020842ae8b6c742b94538baada313d7eb52809
  Version Number:      0.1.2
```

References: https://cwe.mitre.org/data/definitions/613.html

**Comment by malnick** [comment]
@skolenkin - You can find the configuration for token expiration and staleness in the controller configuration docs: https://www.boundaryproject.io/docs/configuration/controller#auth_token_time_to_live and https://www.boundaryproject.io/docs/configuration/controller#auth_token_time_to_stale
