### ISSUE TITLE
Targets audit.log

### ISSUE THREAD

**Issue by mataneine** [hashicorp/boundary#861]
**Is your feature request related to a problem? Please describe.**
We'd like to know which commands the client is executing on the targets 

**Describe the solution you'd like**
 commands executed by clients on targets **audit.log**

**Describe alternatives you've considered**
reverse proxy on the worker nodes?

**Explain any additional use-cases**

- SOC2 type2 compliance
- GDPR compliance
- ITGC compliance

**Comment by mataneine** [comment]
#695

**Comment by PPacent** [comment]
@mataneine , thanks for the suggestion! Session recording for ssh and other protocols is definitely in our vision for Boundary but we don't yet have a timeline for the delivery of this capability. For now, we still have a few big-ticket items for post-launch outlined in our roadmap. For now, I am closing this as a duplicate of issue #695

**Comment by macgahe** [comment]
@mataneine  @PPacent other use cases like PCI-DSS standards required ssh recorded sessions

**Comment by PPacent** [comment]
Closing as dupe of issue #695

**Comment by AdamBouhmad** [comment]
Hey folks! Wanted to x-post to those in this thread that Boundary SSH Session Recording was released today: https://github.com/hashicorp/boundary/issues/695#issuecomment-1589804791

**Comment by mataneine** [comment]
wow, I don't know how I missed it
Thanks!!!

**Comment by mataneine** [comment]
now I realize how I missed it, you released it only for enterprise version :(
