### ISSUE TITLE
target access for a limited time

### ISSUE THREAD

**Issue by ghakfoort** [hashicorp/boundary#868]
It would be nice if it is possible to grant access for a limited period of time. For example: An external contractor needs SSH access to a server but only for 1 day. I want to be able to configure this time frame.

**Comment by malnick** [comment]
Thanks for the question @ghakfoort - you can control target session time using the [session_max_seconds](https://www.boundaryproject.io/docs/concepts/domain-model/targets#session_max_seconds) attribute. Let me know if this is what you were looking for.
