### ISSUE TITLE
enforce / limit specific usernames to access a target

### ISSUE THREAD

**Issue by ghakfoort** [hashicorp/boundary#869]
It would be nice if it is possible to enforce a specific username on a target:

At the moment, I can choose a username as you can see in the example:

"boundary connect ssh -target-id ttcp_zpZEEFVaxI -username geurt"

It would be nice if specific usernames can be allowed to use while accessing a target. If the users public ssh key accidentally
is configured at the root user on a target host, he is able to use "-username root"

**Comment by malnick** [comment]
Thanks for the question @ghakfoort - the `connect ssh` command is a simple wrapper around your local `ssh` client. We don't currently support restricting what can be passed to that client, as the user would have access to the same command and could easily circumvent Boundary doing any kind of filtering to it. That being said, you can apply [a role to a user](https://www.boundaryproject.io/docs/concepts/domain-model/roles) that restricts what targets a user can connect to within Boundary.
