### ISSUE TITLE
Docker Hub images not being updated

### ISSUE THREAD

**Issue by JasonN3** [hashicorp/boundary#949]
**Describe the bug**
The Docker Hub images are not being updated. The latest version on Docker Hub is 0.1.5 while the latest version on GitHub is 0.1.7

**To Reproduce**
1. Browse to https://hub.docker.com/r/hashicorp/boundary/tags?page=1&ordering=last_updated
2. Compare to https://github.com/hashicorp/boundary/releases

**Expected behavior**
Docker Hub should have the latest version

**Additional context**
The Makefile has a section for publishing the built docker image (docker-publish), but it apparently isn't being called during your workflows or at least isn't being called with an account that has access to push.

**Comment by malnick** [comment]
Thanks for the reminder and sorry for the delay on this!

I pushed 0.1.6 and 0.1.7, retagging latest to 0.1.7 this morning.

https://hub.docker.com/layers/hashicorp/boundary/0.1.7/images/sha256-2f5a4244af2b3f4d309dc144e323fad0ae2b39af08a828370f31160883f267eb?context=explore
