### ISSUE TITLE
boundary desktop not able to connect to server

### ISSUE THREAD

**Issue by kesavkolla** [hashicorp/boundary#954]
**Describe the bug**
When trying to connect to the boundary server with TLS enabled the connection is not getting established.

**To Reproduce**
1. Launch boundary destkop
2. Enter server address https://xxx.xxx.xxx.xxx:9200`
3. See error

**Expected behavior**
Connection should get established

**Additional context**
The server uses self signed CA certificate. In mac laptop I've installed the CA certificate and made it to trust everything. When I launch browser and goto https://xxx.xxx.xxx.xxx:9200 I don't see any exception in the certificate. I made sure I've installed the CA certificate in system location in keychain.

**Comment by randallmorey** [comment]
Hi there!  Thank you for your interest in Boundary.  This is an interesting issue for sure and it may come down to the details of the certificate and the CA.  I tried multiple approaches to generating a self-signed CA and certificate for localhost.  It's tricky to get right.

One tool I found that generate valid self-signed certificates is [mkcert](https://github.com/FiloSottile/mkcert).  You might also try using [Vault](http://vaultproject.io).  I was able to get certificates working with Boundary on localhost using these tools.  Boundary Desktop is able to connect to a local dev mode Boundary at `https://localhost:9200`.  Please note this is strictly for development and testing purposes.

I hope this helps!
