### ISSUE TITLE
Feature: expose tcp proxy

### ISSUE THREAD

**Issue by hazcod** [hashicorp/boundary#980]
**Is your feature request related to a problem? Please describe.**
Currently only http is exposed as a connect mechanism, while it uses a handleTcpProxyV1 under the hood.
It would be nice to be able to use raw TCP to e.g. tunnel other protocols over this proxy, with authorization policies on TCP destination IP and port.

**Describe the solution you'd like**
`boundary connect tcp`

**Describe alternatives you've considered**
/

**Comment by JasonN3** [comment]
@hazcod I'm pretty sure this is already implemented. https://github.com/hashicorp/boundary/issues/721 has a similar request. You have to use the configured default port of the target, but otherwise it should work.

**Comment by hazcod** [comment]
@JasonN3 good point. Thanks!
