### ISSUE TITLE
Feature: full http request/response logging

### ISSUE THREAD

**Issue by hazcod** [hashicorp/boundary#983]
**Is your feature request related to a problem? Please describe.**
It would be nice for audit purposes to be able to log full request/response bodies to a component in a performant way.

**Describe the solution you'd like**
Be able to log in an high-performant fashion, e.g. syslog over udp/tcp

**Comment by malnick** [comment]
Thanks for adding this @hazcod - this work is in-progress and I'm roping in our primary contributor on it to update this thread. We don't have a release date yet, but I can say it's in the near term road map, stay tuned!

**Comment by PPacent** [comment]
@hazcod - to follow up on this request, event logging is now available as of [Boundary's 0.5 release](https://www.hashicorp.com/blog/announcing-hashicorp-boundary-0-5). You can read more about these capabilities [here](https://www.boundaryproject.io/docs/configuration/events/overview). I will close this request but please feel free to create a new request for additional observability enhancements.
