### ISSUE TITLE
Feature: Allow pulling vault token from file

### ISSUE THREAD

**Issue by JasonN3** [hashicorp/boundary#987]
**Is your feature request related to a problem? Please describe.**
In order to connect to Vault's Transit engine (https://www.boundaryproject.io/docs/configuration/kms/transit), you need to either specify the token in the configuration file or as an environment file. The Vault agent sidecar stores the token in a separate file.

**Describe the solution you'd like**
Allow token to be read from a file by defining a separate option called token_file.

**Describe alternatives you've considered**
I am currently overriding the entrypoint of the container to cat the token file in to the environment variable and then calling the original entrypoint.

**Explain any additional use-cases**

**Additional context**

**Comment by malnick** [comment]
Hi there! I think you meant to post this on the Vault GitHub page and not Boundary?

**Comment by JasonN3** [comment]
@malnick It would be a change to how Boundary functions not how Vault functions.

I have Boundary running in a Kubernetes cluster with Vault configured to allow authentication with Kubernetes tokens. This allows me to use the Vault sidecar agent to generate a vault token. As of right now, Boundary and the Vault sidecar don't work together because Boundary can only get the vault token from an environment variable or the configuration file. So far my workaround has been to modify the entrypoint of the Boundary container to read the vault token that the Vault agent generated and store it in to an environment variable and then execute Boundary. I'm requesting that the Boundary configuration file be extended to support reading the vault token from a file.

kms "transit" {
  purpose            = "root"
  address            = "https://vault:8200"
  token              = "s.Qf1s5zigZ4OX6akYjQXJC1jY"
  disable_renewal    = "false"

  // Key configuration
  key_name           = "transit_key_name"
  mount_path         = "transit/"
  namespace          = "ns1/"
}

would become

kms "transit" {
  purpose            = "root"
  address            = "https://vault:8200"
  token_file              = "/vault/secrets/token"
  disable_renewal    = "false"

  // Key configuration
  key_name           = "transit_key_name"
  mount_path         = "transit/"
  namespace          = "ns1/"
}

**Comment by malnick** [comment]
@JasonN3 Apologies for the very tardy reply, this looks like we need to make an update to our [shared KMS wrapping library](https://github.com/hashicorp/go-kms-wrapping).

I'll escalate this to an `enhancement` request for pulling that token in as an env var. Thanks for opening this!

**Comment by jefferai** [comment]
@malnick this is already tracked in the linked vault issue as it's a vault API client deficiency. Boundary/gkw are just using that client.
