### ISSUE TITLE
Client Certificate on cluster listener not properly working

### ISSUE THREAD

**Issue by angelbarrera92** [hashicorp/boundary#999]
**Describe the bug**
Controller cluster listener does not validate client certificates

**To Reproduce**
I've got a controller running with the following configuration:

```hcl
controller {
  name        = "example.com boundary controller"
  description = "Official Boundary Controller under example.com"
  database {
    url = "postgresql://boundary:mypassword@mydb:5432/boundary"
  }
  public_cluster_addr = "example.com:9201"
}

listener "tcp" {
  address = "0.0.0.0:443"
  purpose = "api"

  tls_cert_file = "/opt/boundary/certs/live/example.com/fullchain.pem"
  tls_key_file = "/opt/boundary/certs/live/example.com/privkey.pem"
  tls_min_version = "tls13"

  cors_enabled = true
  cors_allowed_origins = ["https://example.com"]
}

listener "tcp" {
  address = "0.0.0.0:9201"
  purpose = "cluster"

  tls_cert_file = "/opt/boundary/certs/live/example.com/fullchain.pem"
  tls_key_file = "/opt/boundary/certs/live/example.com/privkey.pem"
  tls_min_version = "tls13"

  tls_client_ca_file = "/opt/boundary/ca.crt"
  tls_require_and_verify_client_cert = true
}
```

*`kms` blocks have been omitted*

The important bits are under the `cluster` listener.
I'm exposing it using a Let's-encrypt certificate. In addition, I want to validate client certificates with a custom CA.

Right now, any worker can connect to the controller without client certificates.

**Expected behavior**
I expect a fail during worker registration into the controller.

**Additional context**
I don't see any information about how to configure client certificates in the workers

**Comment by jefferai** [comment]
The reason for this is that all of the TLS parameters that you are defining in that `cluster` listener block are being ignored. See https://www.boundaryproject.io/docs/concepts/security/connections-tls#worker-to-controller-tls for more information; we negotiate a TLS handshake using the `worker-auth` KMS block.

I'll update the documentation to make this more clear!

Closing for now but look for an update to the docs soon.

**Comment by angelbarrera92** [comment]
> The reason for this is that all of the TLS parameters that you are defining in that `cluster` listener block are being ignored. See https://www.boundaryproject.io/docs/concepts/security/connections-tls#worker-to-controller-tls for more information; we negotiate a TLS handshake using the `worker-auth` KMS block.
> 
> I'll update the documentation to make this more clear!
> 
> Closing for now but look for an update to the docs soon.

Ok, understood. 
If I may ask you a question regarding this topic...
Can I have multiple KMS worker-auth keys? In a multi-tenant setup, maybe you can create specific keys for specific worker tenants.

Then if a tenant configuration is compromised, you can revoke just that KMS key instead of rolling a new worker tenant configuration for all the tenants.

**Comment by jefferai** [comment]
That's not supported, sorry.
